class ZunoApp {
  constructor(){this.page='settings';this.settingsTab='account';this.counterTimer=null;this.chatFriend=null;this.room=null;}
  get c(){return window.zunoBackend?.client}
  get p(){return window.zunoAuth?.profile}
  esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
  fmt(d){if(!d)return '—';return new Intl.DateTimeFormat('ar-IQ',{dateStyle:'medium'}).format(new Date(d))}
  agoAllowed(last,ms){return !last || Date.now()-new Date(last).getTime()>=ms}
  remain(last,ms){if(!last)return '';const x=ms-(Date.now()-new Date(last).getTime());if(x<=0)return '';const h=Math.ceil(x/3600000);return h>=24?`${Math.ceil(h/24)} يوم`:`${h} ساعة`}
  toast(text,type='ok'){const el=document.getElementById('auth-msg');if(!document.getElementById('auth-screen').classList.contains('hidden')){el.textContent=text;el.className='msg '+type;return}const n=document.createElement('div');n.textContent=text;n.style.cssText='position:fixed;bottom:20px;left:50%;transform:translateX(-50%);z-index:500;background:#101b37;border:1px solid #35528d;padding:10px 14px;border-radius:13px;box-shadow:0 10px 30px #0008';document.body.appendChild(n);setTimeout(()=>n.remove(),2600)}

  async init(){
    this.bindStatic();
    if(!window.zunoBackend.configured) document.getElementById('setup-note').classList.remove('hidden');
    try{const logged=await window.zunoAuth.init();if(logged)this.enterApp();else this.showAuth()}catch(e){this.showAuth();this.toast(e.message,'error')}
  }
  bindStatic(){
    document.querySelectorAll('[data-eye]').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.eye);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'👁':'🙈'});
    document.getElementById('tab-login').onclick=()=>this.authTab('login');document.getElementById('tab-register').onclick=()=>this.authTab('register');
    document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await zunoAuth.login(document.getElementById('login-id').value,document.getElementById('login-pass').value);this.enterApp()}catch(x){this.toast(x.message,'error')}finally{b.disabled=false}};
    document.getElementById('register-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const d=await zunoAuth.register({name:document.getElementById('reg-name').value,email:document.getElementById('reg-email').value,password:document.getElementById('reg-pass').value,confirm:document.getElementById('reg-confirm').value,invite:document.getElementById('reg-invite').value});if(d.session){this.enterApp()}else{this.authTab('login');this.toast('تم إنشاء الحساب. تحقق من البريد إذا كان التأكيد مفعلاً.','ok')}}catch(x){this.toast(x.message,'error')}finally{b.disabled=false}};
    document.getElementById('menu-btn').onclick=()=>this.toggleMenu(true);document.getElementById('overlay').onclick=()=>this.toggleMenu(false);
    document.querySelectorAll('.nav-btn[data-page]').forEach(b=>b.onclick=()=>{this.page=b.dataset.page;document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));this.toggleMenu(false);this.render()});
    document.getElementById('logout-btn').onclick=()=>zunoAuth.logout();
    document.getElementById('bot-fab').onclick=()=>this.openFaq();document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')this.closeModal()};
  }
  authTab(m){document.getElementById('tab-login').classList.toggle('active',m==='login');document.getElementById('tab-register').classList.toggle('active',m==='register');document.getElementById('login-form').classList.toggle('hidden',m!=='login');document.getElementById('register-form').classList.toggle('hidden',m!=='register');document.getElementById('auth-msg').textContent=''}
  showAuth(){document.getElementById('auth-screen').classList.remove('hidden');document.getElementById('app').classList.add('hidden')}
  enterApp(){document.getElementById('auth-screen').classList.add('hidden');document.getElementById('app').classList.remove('hidden');this.page='settings';this.settingsTab='account';this.updateShell();this.render();this.ping();clearInterval(this.presenceTimer);this.presenceTimer=setInterval(()=>this.ping(),60000)}
  async ping(){if(this.c&&this.p)await this.c.rpc('zuno_ping_presence').catch(()=>{})}
  toggleMenu(open){document.getElementById('sidebar').classList.toggle('open',open);document.getElementById('overlay').classList.toggle('hidden',!open)}
  updateShell(){if(!this.p)return;document.getElementById('points').textContent=this.p.points||0;document.getElementById('gems').textContent=this.p.gems||0;const dev=this.p.role==='developer'?'<span class="badge dev">المطور</span>':'';document.getElementById('side-user').innerHTML=`<div class="profile-head"><img class="mini-avatar" src="${this.esc(this.p.avatar_url||'https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Zuno')}"><div><b>${this.esc(this.p.display_name)}</b> ${dev}<div class="muted">ID: ${this.p.public_id}</div></div></div>`}
  async refresh(){await zunoAuth.loadProfile(zunoAuth.user);this.updateShell()}
  render(){clearInterval(this.counterTimer);const m=document.getElementById('main');if(this.page==='settings')this.renderSettings(m);if(this.page==='private')this.renderPrivate(m);if(this.page==='rooms')this.renderRooms(m);if(this.page==='counter')this.renderCounter(m);if(this.page==='store')this.renderStore(m);if(this.page==='wheel')this.renderWheel(m)}

  renderSettings(m){m.innerHTML=`<h1 class="page-title">الإعدادات</h1><div class="section-tabs"><button class="section-tab ${this.settingsTab==='account'?'active':''}" data-st="account">الحساب</button><button class="section-tab ${this.settingsTab==='referral'?'active':''}" data-st="referral">الإحالة</button><button class="section-tab ${this.settingsTab==='support'?'active':''}" data-st="support">الدعم الفني</button></div><div id="settings-body"></div>`;m.querySelectorAll('[data-st]').forEach(b=>b.onclick=()=>{this.settingsTab=b.dataset.st;this.render()});if(this.settingsTab==='account')this.accountView();if(this.settingsTab==='referral')this.referralView();if(this.settingsTab==='support')this.supportView()}
  accountView(){const p=this.p;const nOk=this.agoAllowed(p.name_changed_at,7*864e5),eOk=this.agoAllowed(p.email_changed_at,7*864e5),pwOk=this.agoAllowed(p.password_changed_at,864e5);document.getElementById('settings-body').innerHTML=`<div class="card"><div class="profile-head"><img class="avatar" id="acc-avatar" src="${this.esc(p.avatar_url||'https://api.dicebear.com/9.x/bottts-neutral/svg?seed=Zuno')}"><div><h2 style="margin:0">${this.esc(p.display_name)} ${p.role==='developer'?'<span class="badge dev">المطور</span>':''}</h2><div class="muted">عضو منذ ${this.fmt(p.created_at)}</div></div></div></div><div class="card"><div class="setting-row"><b>ID الحساب</b><input class="field read-only" value="${p.public_id}" readonly></div><div class="setting-row"><b>الاسم</b><div><input id="acc-name" class="field" value="${this.esc(p.display_name)}" ${nOk?'':'disabled'}><div class="note">${nOk?'يمكن تغييره الآن':'التغيير متاح بعد '+this.remain(p.name_changed_at,7*864e5)}</div></div></div><div class="setting-row"><b>البريد الإلكتروني</b><div><input id="acc-email" class="field" value="${this.esc(zunoAuth.user.email||'')}" ${eOk?'':'disabled'}><div class="note">${eOk?'يمكن تغييره الآن':'التغيير متاح بعد '+this.remain(p.email_changed_at,7*864e5)}</div></div></div><div class="setting-row"><b>كلمة المرور الجديدة</b><div><div class="field-wrap"><input id="acc-pass" type="password" class="field" placeholder="اتركها فارغة إن لم ترد تغييرها" ${pwOk?'':'disabled'}><button class="eye" type="button" id="acc-eye">👁</button></div><div class="note">${pwOk?'مرة واحدة كل 24 ساعة':'التغيير متاح بعد '+this.remain(p.password_changed_at,864e5)}</div></div></div><div class="setting-row"><b>صورة الحساب</b><input id="acc-avatar-url" class="field" value="${this.esc(p.avatar_url||'')}" placeholder="رابط الصورة"></div><div class="setting-row"><b>رقم الهاتف</b><div><input class="field read-only" placeholder="إضافة رقم هاتف" disabled><span class="coming">قريبًا</span></div></div><button id="save-account" class="btn">حفظ التغييرات</button></div>`;document.getElementById('acc-eye').onclick=()=>{const i=document.getElementById('acc-pass');i.type=i.type==='password'?'text':'password'};document.getElementById('save-account').onclick=()=>this.saveAccount()}
  async saveAccount(){const p=this.p;const name=document.getElementById('acc-name')?.value.trim(),email=document.getElementById('acc-email')?.value.trim(),password=document.getElementById('acc-pass')?.value,avatar=document.getElementById('acc-avatar-url')?.value.trim();try{if(avatar!==p.avatar_url){const {error}=await this.c.rpc('zuno_update_avatar',{p_avatar_url:avatar||null});if(error)throw error}if(name&&name!==p.display_name){const {error}=await this.c.rpc('zuno_update_display_name',{p_name:name});if(error)throw error}if((email&&email!==zunoAuth.user.email)||password){const {data,error}=await this.c.functions.invoke('account-update',{body:{email:email!==zunoAuth.user.email?email:null,password:password||null}});if(error||!data?.ok)throw new Error(data?.error||'تعذر تحديث بيانات الدخول')}await this.refresh();this.toast('تم حفظ التغييرات');this.render()}catch(e){this.toast(e.message||'تعذر الحفظ','error')}}
  async referralView(){document.getElementById('settings-body').innerHTML=`<div class="card"><h2>الإحالة</h2><p class="muted">ID الدعوة الخاص بك هو نفس ID حسابك الثابت.</p><div class="list-item"><div><div class="muted">ID الدعوة الخاص بي</div><b style="font-size:28px">${this.p.public_id}</b></div><button id="copy-ref" class="btn secondary">نسخ ID</button></div><div id="ref-count" class="card">جارِ تحميل عدد الإحالات...</div></div>`;document.getElementById('copy-ref').onclick=async()=>{await navigator.clipboard?.writeText(String(this.p.public_id));this.toast('تم نسخ ID')};const{data}=await this.c.rpc('zuno_referral_count');document.getElementById('ref-count').innerHTML=`👥 دخل عن طريق إحالتك: <b>${data||0}</b> شخص`}
  supportOpen(){const f=new Intl.DateTimeFormat('en-GB',{timeZone:window.ZUNO_CONFIG.SUPPORT_TIMEZONE,hour:'2-digit',hour12:false}).formatToParts(new Date());const h=Number(f.find(x=>x.type==='hour').value);return h>=8&&h<20}
  supportView(){const open=this.supportOpen();document.getElementById('settings-body').innerHTML=`<div class="card"><h2>الدعم الفني</h2><p>موظف استقبال الشكاوى</p><p class="${open?'support-open':'support-closed'}"><b>${open?'● متاح الآن':'● خارج ساعات العمل'}</b></p><p class="muted">ساعات العمل: 8:00 صباحًا – 8:00 مساءً بتوقيت بغداد.</p><textarea id="support-msg" class="field" rows="5" placeholder="اكتب الشكوى أو الاستفسار"></textarea><button id="send-support" class="btn" style="margin-top:10px">إرسال</button><p class="note">${open?'سيتم تسجيل رسالتك للدعم.':'يمكنك إرسال الرسالة الآن وستبقى محفوظة حتى بدء الدوام.'}</p></div><div class="card"><b>🤖 بوت Zuno</b><p class="muted">اضغط على مجسم البوت أسفل الشاشة لعرض الأسئلة الشائعة.</p></div>`;document.getElementById('send-support').onclick=()=>this.sendSupport()}
  async sendSupport(){const body=document.getElementById('support-msg').value.trim();if(!body)return this.toast('اكتب رسالتك','error');const{error}=await this.c.rpc('zuno_create_support_ticket',{p_message:body});if(error)return this.toast(error.message,'error');document.getElementById('support-msg').value='';this.toast('تم إرسال رسالتك للدعم')}

  renderPrivate(m){m.innerHTML=`<h1 class="page-title">الخاص</h1><div class="card"><h3>البحث عن صديق</h3><div class="grid two"><input id="friend-id" class="field" inputmode="numeric" placeholder="ID المستخدم"><input id="friend-note" class="field" maxlength="120" placeholder="نبذة مع طلب الصداقة (اختياري)"></div><button id="find-friend" class="btn" style="margin-top:10px">بحث</button><div id="friend-search"></div></div><div class="card"><h3>طلبات الصداقة</h3><div id="requests">جارِ التحميل...</div></div><div class="card"><h3>الأصدقاء</h3><div id="friends">جارِ التحميل...</div></div>`;document.getElementById('find-friend').onclick=()=>this.findFriend();this.loadPrivateLists()}
  async findFriend(){const id=Number(document.getElementById('friend-id').value);if(!id)return;const{data,error}=await this.c.rpc('zuno_find_user',{p_public_id:id});const box=document.getElementById('friend-search');if(error||!data?.length){box.innerHTML='<p class="muted">لم يتم العثور على المستخدم.</p>';return}const u=data[0];box.innerHTML=`<div class="list-item"><div class="user-info"><img class="mini-avatar" src="${this.esc(u.avatar_url||'https://api.dicebear.com/9.x/bottts-neutral/svg?seed='+u.public_id)}"><div><b>${this.esc(u.display_name)}</b><div class="muted">ID: ${u.public_id}</div></div></div><button id="send-friend" class="mini-btn">إرسال طلب</button></div>`;document.getElementById('send-friend').onclick=async()=>{const note=document.getElementById('friend-note').value.trim();const{error}=await this.c.rpc('zuno_send_friend_request',{p_public_id:u.public_id,p_note:note||null});if(error)this.toast(error.message,'error');else{this.toast('تم إرسال طلب الصداقة');this.loadPrivateLists()}}}
  async loadPrivateLists(){const req=document.getElementById('requests'),fr=document.getElementById('friends');const{data:r}=await this.c.rpc('zuno_pending_friend_requests');req.innerHTML=(r||[]).length?(r||[]).map(x=>`<div class="list-item"><div><b>${this.esc(x.display_name)}</b> <span class="muted">ID ${x.public_id}</span><div class="note">${this.esc(x.note||'بدون نبذة')}</div></div><div class="actions"><button class="mini-btn" data-accept="${x.request_id}">موافقة</button><button class="mini-btn red" data-reject="${x.request_id}">رفض</button></div></div>`).join(''):'<p class="muted">لا توجد طلبات جديدة.</p>';req.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>this.respondFriend(b.dataset.accept,'accepted'));req.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>this.respondFriend(b.dataset.reject,'rejected'));const{data:f}=await this.c.rpc('zuno_get_friends');fr.innerHTML=(f||[]).length?(f||[]).map(x=>`<div class="list-item"><div class="user-info"><img class="mini-avatar" src="${this.esc(x.avatar_url||'https://api.dicebear.com/9.x/bottts-neutral/svg?seed='+x.public_id)}"><div><b>${this.esc(x.display_name)}</b><div><span class="status-dot ${x.is_online?'online':''}"></span> ${x.is_online?'متصل الآن':'غير متصل'} · ID ${x.public_id}</div></div></div><button class="mini-btn" data-chat="${x.public_id}">مراسلة</button></div>`).join(''):'<p class="muted">لا يوجد أصدقاء بعد.</p>';fr.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>this.openChat(Number(b.dataset.chat)))}
  async respondFriend(id,action){const{error}=await this.c.rpc('zuno_respond_friend_request',{p_request_id:id,p_action:action});if(error)this.toast(error.message,'error');else{this.toast(action==='accepted'?'تمت الموافقة':'تم الرفض');this.loadPrivateLists()}}
  async openChat(publicId){const{data:u}=await this.c.rpc('zuno_find_user',{p_public_id:publicId});const user=u?.[0];if(!user)return;this.openModal(`<button class="close" onclick="zunoApp.closeModal()">✕</button><h3>محادثة مع ${this.esc(user.display_name)}</h3><div id="chat-box" class="chat-box"></div><div class="grid" style="grid-template-columns:1fr auto;margin-top:10px"><input id="chat-input" class="field" placeholder="اكتب رسالة"><button id="chat-send" class="btn">إرسال</button></div>`);this.chatFriend=publicId;await this.loadChat();document.getElementById('chat-send').onclick=()=>this.sendChat()}
  async loadChat(){const{data}=await this.c.rpc('zuno_get_private_messages',{p_public_id:this.chatFriend});const box=document.getElementById('chat-box');if(!box)return;box.innerHTML=(data||[]).map(x=>`<div class="bubble ${x.sender_public_id===this.p.public_id?'me':''}">${this.esc(x.body)}<div class="note">${new Date(x.created_at).toLocaleTimeString('ar-IQ',{hour:'2-digit',minute:'2-digit'})}</div></div>`).join('');box.scrollTop=box.scrollHeight}
  async sendChat(){const i=document.getElementById('chat-input'),body=i.value.trim();if(!body)return;const{error}=await this.c.rpc('zuno_send_private_message',{p_public_id:this.chatFriend,p_body:body});if(error)return this.toast(error.message,'error');i.value='';this.loadChat()}

  renderRooms(m){m.innerHTML=`<h1 class="page-title">الرومات</h1><div class="card"><h3>إنشاء روم <span class="price">500 نقطة</span></h3><div class="grid two"><input id="room-name" class="field" placeholder="اسم الروم"><input id="room-image" class="field" placeholder="رابط صورة الروم (اختياري)"><input id="room-bio" class="field" placeholder="نبذة عن الروم"><input id="room-pass" class="field" inputmode="numeric" maxlength="4" placeholder="رقم سري 1-4 أرقام (اختياري)"></div><button id="create-room" class="btn" style="margin-top:10px">إنشاء بـ 500 نقطة</button></div><div class="card"><h3>البحث عن روم</h3><div class="grid two"><input id="room-search" class="field" inputmode="numeric" placeholder="ID الروم أو ID صاحب الروم"><button id="search-room" class="btn">بحث</button></div><div id="room-results"></div></div><div class="card"><h3>الرومات المتاحة</h3><div id="rooms-list">جارِ التحميل...</div></div>`;document.getElementById('create-room').onclick=()=>this.createRoom();document.getElementById('search-room').onclick=()=>this.searchRooms();this.loadRooms()}
  async createRoom(){const name=room_name.value.trim(),image=room_image.value.trim(),bio=room_bio.value.trim(),pass=room_pass.value.trim();if(!name)return this.toast('أدخل اسم الروم','error');if(pass&&!/^\d{1,4}$/.test(pass))return this.toast('الرقم السري من 1 إلى 4 أرقام','error');const{data,error}=await this.c.rpc('zuno_create_room',{p_name:name,p_image_url:image||null,p_bio:bio||null,p_password:pass||null});if(error)return this.toast(error.message,'error');await this.refresh();this.toast(`تم إنشاء الروم ID ${data}`);this.loadRooms()}
  async loadRooms(){const{data}=await this.c.rpc('zuno_list_rooms');this.paintRooms('rooms-list',data||[])}
  async searchRooms(){const q=Number(room_search.value);if(!q)return;const{data}=await this.c.rpc('zuno_search_rooms',{p_query:q});this.paintRooms('room-results',data||[])}
  paintRooms(id,arr){const el=document.getElementById(id);if(!el)return;el.innerHTML=arr.length?arr.map(r=>`<div class="list-item"><div><b>${this.esc(r.name)}</b> ${r.is_locked?'<span class="room-lock">🔒</span>':''}<div class="muted">Room ID ${r.room_public_id} · المالك ID ${r.owner_public_id}</div><div class="note">${this.esc(r.bio||'')}</div></div><button class="mini-btn" data-room="${r.room_public_id}" data-locked="${r.is_locked}">دخول</button></div>`).join(''):'<p class="muted">لا توجد نتائج.</p>';el.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>this.joinRoom(Number(b.dataset.room),b.dataset.locked==='true'))}
  async joinRoom(id,locked){let password=null;if(locked)password=prompt('أدخل الرقم السري للروم');const{data,error}=await this.c.rpc('zuno_join_room',{p_room_public_id:id,p_password:password});if(error)return this.toast(error.message,'error');this.room=id;this.roomView()}
  async roomView(){const{data:r,error}=await this.c.rpc('zuno_room_details',{p_room_public_id:this.room});if(error||!r?.length)return this.toast('تعذر فتح الروم','error');const room=r[0];document.getElementById('main').innerHTML=`<button class="mini-btn" id="back-rooms">← رجوع</button><h1 class="page-title">${this.esc(room.name)}</h1><div class="card"><div><b>مالك الروم:</b> ${this.esc(room.owner_name)} <span class="badge">مالك الروم</span></div><div class="muted">Room ID ${room.room_public_id}</div><p>${this.esc(room.bio||'')}</p><div class="actions"><span class="coming">🎵 الأغاني قريبًا</span><span class="coming">🎤 شراء 4/6/8 مايكات قريبًا</span><span class="coming">🎁 هدايا الحيوانات 100–5000 قريبًا</span></div></div><div class="grid two"><div class="card"><h3>الدردشة</h3><div id="room-chat" class="chat-box"></div><div class="grid" style="grid-template-columns:1fr auto;margin-top:8px"><input id="room-msg" class="field"><button id="room-send" class="btn">إرسال</button></div></div><div class="card"><h3>الأعضاء</h3><div id="room-members"></div></div></div>`;document.getElementById('back-rooms').onclick=()=>{this.page='rooms';this.render()};document.getElementById('room-send').onclick=()=>this.sendRoomMessage();await this.loadRoomChat();await this.loadRoomMembers();}
  async loadRoomChat(){const{data}=await this.c.rpc('zuno_get_room_messages',{p_room_public_id:this.room});const el=document.getElementById('room-chat');if(el)el.innerHTML=(data||[]).map(x=>`<div class="bubble ${x.sender_public_id===this.p.public_id?'me':''}"><b>${this.esc(x.display_name)}</b> <span class="note">${x.member_role==='owner'?'مالك الروم':x.member_role==='moderator'?'مشرف':''}</span><br>${this.esc(x.body)}</div>`).join('')}
  async sendRoomMessage(){const i=document.getElementById('room-msg'),b=i.value.trim();if(!b)return;const{error}=await this.c.rpc('zuno_send_room_message',{p_room_public_id:this.room,p_body:b});if(error)return this.toast(error.message,'error');i.value='';this.loadRoomChat()}
  async loadRoomMembers(){const{data}=await this.c.rpc('zuno_room_members',{p_room_public_id:this.room});const me=(data||[]).find(x=>x.public_id===this.p.public_id),can=me&&['owner','moderator'].includes(me.member_role);const el=document.getElementById('room-members');el.innerHTML=(data||[]).map(x=>`<div class="list-item"><div><b>${this.esc(x.display_name)}</b><div class="note">ID ${x.public_id} · ${x.member_role==='owner'?'مالك الروم':x.member_role==='moderator'?'مشرف':'عضو'}</div></div>${can&&x.public_id!==this.p.public_id?`<button class="mini-btn" data-manage="${x.public_id}">إدارة</button>`:''}</div>`).join('');el.querySelectorAll('[data-manage]').forEach(b=>b.onclick=()=>this.manageRoomMember(Number(b.dataset.manage),me.member_role))}
  manageRoomMember(id,myRole){const owner=myRole==='owner';this.openModal(`<button class="close" onclick="zunoApp.closeModal()">✕</button><h3>إدارة العضو ID ${id}</h3><div class="grid">${owner?'<button class="btn secondary" data-act="promote">رفع مشرف</button><button class="btn secondary" data-act="demote">تنزيل إلى عضو</button>':''}<button class="btn secondary" data-act="mute_temp">كتم مؤقت 10 دقائق</button><button class="btn secondary" data-act="mute_perm">كتم دائم</button><button class="btn secondary" data-act="unmute">إلغاء الكتم</button><button class="btn secondary" data-act="kick">طرد</button><button class="btn danger" data-act="ban">حظر</button></div>`);document.querySelectorAll('[data-act]').forEach(b=>b.onclick=async()=>{const{error}=await this.c.rpc('zuno_room_action',{p_room_public_id:this.room,p_target_public_id:id,p_action:b.dataset.act,p_minutes:b.dataset.act==='mute_temp'?10:null});if(error)this.toast(error.message,'error');else{this.closeModal();this.toast('تم تنفيذ الإجراء');this.loadRoomMembers()}})}

  renderCounter(m){m.innerHTML=`<h1 class="page-title">العداد</h1><div class="card"><div class="hourglass-stage"><div id="hourglass" class="hourglass"><div class="hourglass-frame"></div><div class="glass"></div><div class="sand-top"></div><div class="sand-stream"></div><div class="sand-bottom"></div></div></div><div id="counter-time" class="counter-time">24:00:00</div><p id="counter-status" class="muted" style="text-align:center">جاهز للتفعيل</p><div style="text-align:center"><button id="counter-action" class="btn">تفعيل العداد</button></div><p class="note" style="text-align:center">بعد التفعيل لا يمكن إيقاف العداد أو التلاعب بوقته. المكافأة: 50 💎 مجوهرة بعد 24 ساعة.</p></div><h2>شراء عداد</h2><div class="grid three">${this.counterShop('🪵','خشبي','500')}${this.counterShop('🪨','حجري','750')}${this.counterShop('⚙️','حديدي','1000')}${this.counterShop('🔮','متقدم','2000')}${this.counterShop('👑','مميز','4000')}</div>`;document.getElementById('counter-action').onclick=()=>this.counterAction();this.updateCounter();this.counterTimer=setInterval(()=>this.updateCounter(),1000)}
  counterShop(i,n,p){return `<div class="card shop-card"><div><div class="shop-icon">${i}</div><b>عداد ${n}</b><div class="price">${p} نقطة</div><span class="coming">قريبًا</span></div></div>`}
  counterState(){const s=this.p.counter_started_at?new Date(this.p.counter_started_at).getTime():0;if(!s)return{state:'idle',rem:864e5};const end=s+864e5,rem=end-Date.now();return rem>0?{state:'running',rem}:{state:'ready',rem:0}}
  updateCounter(){const st=this.counterState(),h=document.getElementById('hourglass'),t=document.getElementById('counter-time'),s=document.getElementById('counter-status'),b=document.getElementById('counter-action');if(!h)return;const elapsed=st.state==='running'?864e5-st.rem:st.state==='ready'?864e5:0;h.style.setProperty('--sand',`${Math.max(0,100-(elapsed/864e5*100))}%`);h.classList.toggle('done',st.state!=='running');if(st.state==='running'){const sec=Math.ceil(st.rem/1000),hh=Math.floor(sec/3600),mm=Math.floor(sec%3600/60),ss=sec%60;t.textContent=[hh,mm,ss].map(x=>String(x).padStart(2,'0')).join(':');s.textContent='الرمل يتحرك الآن';b.textContent='العداد يعمل';b.disabled=true}else if(st.state==='ready'){t.textContent='00:00:00';s.textContent='اكتمل العداد — استلم مكافأتك';b.textContent='استلام 50 مجوهرة';b.disabled=false}else{t.textContent='24:00:00';s.textContent='جاهز للتفعيل';b.textContent='تفعيل العداد';b.disabled=false}}
  async counterAction(){const st=this.counterState();const h=document.getElementById('hourglass');if(st.state==='idle'){h.classList.add('flip');const{error}=await this.c.rpc('zuno_start_counter');setTimeout(()=>h.classList.remove('flip'),900);if(error)return this.toast(error.message,'error');await this.refresh();this.renderCounter(document.getElementById('main'));this.toast('تم تشغيل العداد لمدة 24 ساعة')}else if(st.state==='ready'){const{data,error}=await this.c.rpc('zuno_claim_counter_reward');if(error)return this.toast(error.message,'error');await this.refresh();this.renderCounter(document.getElementById('main'));this.toast(`تمت إضافة ${data?.reward||50} مجوهرة`)}}

  renderStore(m){m.innerHTML=`<h1 class="page-title">المتجر</h1><div class="grid two">${this.storeCard('🪪','ID مميز','الأرقام من 10 إلى 100','قريبًا')}${this.storeCard('✨','المظهر','إطار الحساب · اسم فريد · دخول فخم للرومات','قريبًا')}${this.storeCard('📱','الموبايل','قسم الموبايل','قريبًا')}${this.storeCard('💻','الحاسوب','قسم الحاسوب','قريبًا')}${this.storeCard('📲','الأرصدة','آسياسيل · زين · كورك','قريبًا')}</div>`}
  storeCard(i,n,d,c){return `<div class="card shop-card"><div><div class="shop-icon">${i}</div><h3>${n}</h3><p class="muted">${d}</p><span class="coming">${c}</span></div></div>`}
  renderWheel(m){m.innerHTML=`<h1 class="page-title">العجلة</h1><div class="grid two"><div class="card shop-card"><div><div class="shop-icon">🎡💎</div><h2>عجلة المجوهرات</h2><p class="muted">عجلة خاصة بالمجوهرات.</p><span class="coming">قريبًا</span></div></div><div class="card shop-card"><div><div class="shop-icon">🏆</div><h2>تحدي النقاط</h2><p class="muted">4 لاعبين · نظام التحدي سيتم إطلاقه لاحقًا.</p><span class="coming">قريبًا</span></div></div></div>`}

  openFaq(){this.openModal(`<button class="close" onclick="zunoApp.closeModal()">✕</button><h2>🤖 بوت Zuno</h2><p class="muted">اختر سؤالًا شائعًا:</p>${[['كيف أغير كلمة المرور؟','من الإعدادات ← الحساب. يمكن تغييرها مرة كل 24 ساعة.'],['كيف أغير الاسم؟','من الإعدادات ← الحساب. الاسم يتغير مرة كل 7 أيام.'],['أين أجد ID؟','يوجد داخل صفحة الحساب وهو ثابت ولا يمكن تغييره.'],['كيف تعمل الإحالة؟','شارك ID حسابك، ويمكن للمستخدم الجديد إدخاله بشكل اختياري أثناء التسجيل.'],['كيف أحصل على المجوهرات؟','فعّل العداد 24 ساعة ثم استلم 50 مجوهرة.'],['كيف أتواصل مع الدعم؟','الإعدادات ← الدعم الفني. الدوام من 8 صباحًا إلى 8 مساءً بتوقيت بغداد.']].map(x=>`<button class="faq" data-answer="${this.esc(x[1])}">${x[0]}</button>`).join('')}<div id="faq-answer" class="card muted">اضغط على سؤال لعرض الإجابة.</div>`);document.querySelectorAll('.faq').forEach(b=>b.onclick=()=>document.getElementById('faq-answer').textContent=b.dataset.answer)}
  openModal(html){document.getElementById('modal-card').innerHTML=html;document.getElementById('modal').classList.remove('hidden')}
  closeModal(){document.getElementById('modal').classList.add('hidden')}
}
window.zunoApp=new ZunoApp();
document.addEventListener('DOMContentLoaded',()=>window.zunoApp.init());
