window.ZUNO_CONFIG = {
  SUPABASE_URL: "PASTE_SUPABASE_PROJECT_URL_HERE",
  SUPABASE_ANON_KEY: "PASTE_SUPABASE_ANON_KEY_HERE",
  APP_NAME: "Zuno",
  SUPPORT_TIMEZONE: "Asia/Baghdad",
  SUPPORT_OPEN_HOUR: 8,
  SUPPORT_CLOSE_HOUR: 20
};
