-- ZONO protected developer account-query console
-- Run once in Supabase SQL Editor after the previous developer ban/unban SQL.
-- Adds a second secret lock, user account lookup, exact/fallback daily seed lookup,
-- and a developer-only seed reset action with audit logging.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.zono_developer_console_lock (
    developer_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    pin_hash text NOT NULL,
    failed_attempts integer NOT NULL DEFAULT 0,
    locked_until timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.zono_developer_console_sessions (
    token_hash text PRIMARY KEY,
    developer_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS zono_developer_console_sessions_dev_idx
    ON public.zono_developer_console_sessions(developer_id);
CREATE INDEX IF NOT EXISTS zono_developer_console_sessions_exp_idx
    ON public.zono_developer_console_sessions(expires_at);

CREATE TABLE IF NOT EXISTS public.zono_developer_console_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    target_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    target_public_id bigint,
    action text NOT NULL,
    before_data jsonb,
    after_data jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.zono_developer_console_lock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zono_developer_console_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zono_developer_console_audit ENABLE ROW LEVEL SECURITY;

-- No direct client table access is granted. Everything goes through SECURITY DEFINER RPCs.
REVOKE ALL ON public.zono_developer_console_lock FROM anon, authenticated;
REVOKE ALL ON public.zono_developer_console_sessions FROM anon, authenticated;
REVOKE ALL ON public.zono_developer_console_audit FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.zono__require_developer()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_role text;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'NOT_AUTHENTICATED';
    END IF;
    SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
    IF COALESCE(v_role, '') <> 'developer' THEN
        RAISE EXCEPTION 'DEVELOPER_ONLY';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono__developer_console_session_ok(p_token text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_hash text;
    v_ok boolean;
BEGIN
    PERFORM public.zono__require_developer();
    IF NULLIF(btrim(COALESCE(p_token,'')), '') IS NULL THEN
        RETURN false;
    END IF;
    v_hash := encode(digest(p_token, 'sha256'), 'hex');
    DELETE FROM public.zono_developer_console_sessions WHERE expires_at <= now();
    SELECT EXISTS(
        SELECT 1
        FROM public.zono_developer_console_sessions
        WHERE token_hash = v_hash
          AND developer_id = auth.uid()
          AND expires_at > now()
    ) INTO v_ok;
    RETURN COALESCE(v_ok,false);
END;
$$;

REVOKE ALL ON FUNCTION public.zono__require_developer() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.zono__developer_console_session_ok(text) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.zono_developer_console_status()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_configured boolean := false;
    v_locked_until timestamptz;
BEGIN
    PERFORM public.zono__require_developer();
    SELECT true, locked_until
      INTO v_configured, v_locked_until
      FROM public.zono_developer_console_lock
     WHERE developer_id = auth.uid();

    RETURN jsonb_build_object(
        'configured', COALESCE(v_configured,false),
        'locked', (v_locked_until IS NOT NULL AND v_locked_until > now()),
        'locked_until', v_locked_until
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_console_set_pin(p_pin text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_pin text := COALESCE(p_pin,'');
BEGIN
    PERFORM public.zono__require_developer();
    IF char_length(v_pin) < 6 OR char_length(v_pin) > 32 THEN
        RAISE EXCEPTION 'INVALID_PIN_LENGTH';
    END IF;
    IF EXISTS (SELECT 1 FROM public.zono_developer_console_lock WHERE developer_id = auth.uid()) THEN
        RAISE EXCEPTION 'PIN_ALREADY_CONFIGURED';
    END IF;

    INSERT INTO public.zono_developer_console_lock(developer_id,pin_hash)
    VALUES (auth.uid(), crypt(v_pin, gen_salt('bf', 10)));

    RETURN jsonb_build_object('ok',true);
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_console_unlock(p_pin text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_row public.zono_developer_console_lock%ROWTYPE;
    v_token text;
    v_token_hash text;
    v_expires timestamptz := now() + interval '10 minutes';
    v_failures integer;
BEGIN
    PERFORM public.zono__require_developer();

    SELECT * INTO v_row
      FROM public.zono_developer_console_lock
     WHERE developer_id = auth.uid()
     FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'PIN_NOT_CONFIGURED';
    END IF;

    IF v_row.locked_until IS NOT NULL AND v_row.locked_until > now() THEN
        RAISE EXCEPTION 'CONSOLE_LOCKED';
    END IF;

    IF crypt(COALESCE(p_pin,''), v_row.pin_hash) <> v_row.pin_hash THEN
        v_failures := COALESCE(v_row.failed_attempts,0) + 1;
        UPDATE public.zono_developer_console_lock
           SET failed_attempts = CASE WHEN v_failures >= 5 THEN 0 ELSE v_failures END,
               locked_until = CASE WHEN v_failures >= 5 THEN now() + interval '10 minutes' ELSE NULL END,
               updated_at = now()
         WHERE developer_id = auth.uid();
        IF v_failures >= 5 THEN
            RAISE EXCEPTION 'CONSOLE_LOCKED';
        END IF;
        RAISE EXCEPTION 'INVALID_PIN';
    END IF;

    UPDATE public.zono_developer_console_lock
       SET failed_attempts = 0, locked_until = NULL, updated_at = now()
     WHERE developer_id = auth.uid();

    DELETE FROM public.zono_developer_console_sessions
     WHERE developer_id = auth.uid() OR expires_at <= now();

    v_token := encode(gen_random_bytes(32), 'hex');
    v_token_hash := encode(digest(v_token, 'sha256'), 'hex');
    INSERT INTO public.zono_developer_console_sessions(token_hash,developer_id,expires_at)
    VALUES (v_token_hash,auth.uid(),v_expires);

    RETURN jsonb_build_object('ok',true,'token',v_token,'expires_at',v_expires);
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_console_lock_session(p_token text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_hash text;
BEGIN
    PERFORM public.zono__require_developer();
    v_hash := encode(digest(COALESCE(p_token,''), 'sha256'), 'hex');
    DELETE FROM public.zono_developer_console_sessions
     WHERE token_hash = v_hash AND developer_id = auth.uid();
    RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_query_users(
    p_token text,
    p_query text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_q text := btrim(COALESCE(p_query,''));
    v_result jsonb;
BEGIN
    IF NOT public.zono__developer_console_session_ok(p_token) THEN
        RAISE EXCEPTION 'INVALID_CONSOLE_SESSION';
    END IF;

    SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.public_id), '[]'::jsonb)
      INTO v_result
      FROM (
        SELECT public_id,
               username,
               display_name,
               COALESCE(account_level,1) AS account_level
          FROM public.profiles
         WHERE public_id IS NOT NULL
           AND (
                v_q = ''
                OR public_id::text = regexp_replace(v_q,'[^0-9]','','g')
                OR COALESCE(display_name,'') ILIKE '%' || v_q || '%'
                OR COALESCE(username,'') ILIKE '%' || v_q || '%'
           )
         ORDER BY public_id
         LIMIT 200
      ) x;
    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_user_details(
    p_token text,
    p_public_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_target public.profiles%ROWTYPE;
    v_caller uuid := auth.uid();
    v_original_sub text := current_setting('request.jwt.claim.sub', true);
    v_totals jsonb := '{}'::jsonb;
    v_daily numeric := 0;
    v_has_counter boolean := false;
BEGIN
    IF NOT public.zono__developer_console_session_ok(p_token) THEN
        RAISE EXCEPTION 'INVALID_CONSOLE_SESSION';
    END IF;

    SELECT * INTO v_target FROM public.profiles WHERE public_id = p_public_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'USER_NOT_FOUND';
    END IF;

    -- Ask the application's existing daily-total RPC as the selected user.
    -- This preserves the same economy calculation used by the live counter,
    -- including repeated bird purchases when that RPC is installed.
    BEGIN
        PERFORM set_config('request.jwt.claim.sub', v_target.id::text, true);
        EXECUTE 'SELECT to_jsonb(public.zono_bird_daily_totals())' INTO v_totals;
        PERFORM set_config('request.jwt.claim.sub', COALESCE(v_original_sub, v_caller::text), true);
        v_daily := COALESCE((v_totals->>'seeds_daily')::numeric,0);
    EXCEPTION WHEN OTHERS THEN
        PERFORM set_config('request.jwt.claim.sub', COALESCE(v_original_sub, v_caller::text), true);
        -- Fallback for older database versions: use current active bird rank.
        v_daily := CASE COALESCE(v_target.active_bird_rank,0)
            WHEN 1 THEN 500
            WHEN 2 THEN 750
            WHEN 3 THEN 1000
            WHEN 4 THEN 1500
            WHEN 5 THEN 2500
            ELSE 0
        END;
    END;

    v_has_counter := COALESCE(v_target.active_bird_rank,0) > 0
                     OR (v_target.bird_plan_ends_at IS NOT NULL AND v_target.bird_plan_ends_at > now());

    RETURN jsonb_build_object(
        'public_id', v_target.public_id,
        'username', v_target.username,
        'display_name', v_target.display_name,
        'account_level', COALESCE(v_target.account_level,1),
        'seeds', COALESCE(v_target.seeds,0),
        'feathers', COALESCE(v_target.feathers,0),
        'daily_seeds', COALESCE(v_daily,0),
        'has_counter', v_has_counter,
        'active_bird_rank', COALESCE(v_target.active_bird_rank,0),
        'active_bird', v_target.active_bird,
        'bird_plan_ends_at', v_target.bird_plan_ends_at
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_zero_user_seeds(
    p_token text,
    p_public_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_target_id uuid;
    v_before bigint;
BEGIN
    IF NOT public.zono__developer_console_session_ok(p_token) THEN
        RAISE EXCEPTION 'INVALID_CONSOLE_SESSION';
    END IF;

    SELECT id, COALESCE(seeds,0)::bigint
      INTO v_target_id, v_before
      FROM public.profiles
     WHERE public_id = p_public_id
     FOR UPDATE;

    IF v_target_id IS NULL THEN
        RAISE EXCEPTION 'USER_NOT_FOUND';
    END IF;

    UPDATE public.profiles SET seeds = 0 WHERE id = v_target_id;

    INSERT INTO public.zono_developer_console_audit(
        developer_id,target_user_id,target_public_id,action,before_data,after_data
    ) VALUES (
        auth.uid(),v_target_id,p_public_id,'zero_seeds',
        jsonb_build_object('seeds',v_before),
        jsonb_build_object('seeds',0)
    );

    RETURN jsonb_build_object(
        'ok',true,
        'public_id',p_public_id,
        'previous_seeds',v_before,
        'seeds',0
    );
END;
$$;

-- Public RPC grants: internal helper functions stay revoked.
REVOKE ALL ON FUNCTION public.zono_developer_console_status() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.zono_developer_console_set_pin(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.zono_developer_console_unlock(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.zono_developer_console_lock_session(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.zono_developer_query_users(text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.zono_developer_user_details(text,bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.zono_developer_zero_user_seeds(text,bigint) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.zono_developer_console_status() TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_developer_console_set_pin(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_developer_console_unlock(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_developer_console_lock_session(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_developer_query_users(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_developer_user_details(text,bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_developer_zero_user_seeds(text,bigint) TO authenticated;
