
-- ZONO Developer Query Console - remaining RPC repair
-- نفّذ الملف كاملاً في Supabase SQL Editor

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.zono_developer_console_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    developer_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    target_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    target_public_id bigint,
    action text NOT NULL,
    before_data jsonb,
    after_data jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.zono_developer_console_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.zono_developer_console_audit FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.zono__developer_console_session_ok(p_token text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
    v_hash text;
    v_ok boolean;
BEGIN
    PERFORM public.zono__require_developer();

    IF NULLIF(btrim(COALESCE(p_token,'')), '') IS NULL THEN
        RETURN false;
    END IF;

    v_hash := encode(digest(p_token, 'sha256'), 'hex');

    DELETE FROM public.zono_developer_console_sessions
    WHERE expires_at <= now();

    SELECT EXISTS(
        SELECT 1
        FROM public.zono_developer_console_sessions
        WHERE token_hash = v_hash
          AND developer_id = auth.uid()
          AND expires_at > now()
    )
    INTO v_ok;

    RETURN COALESCE(v_ok,false);
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_query_users(
    p_token text,
    p_query text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
    v_q text := btrim(COALESCE(p_query,''));
    v_result jsonb;
BEGIN
    IF NOT public.zono__developer_console_session_ok(p_token) THEN
        RAISE EXCEPTION 'INVALID_CONSOLE_SESSION';
    END IF;

    SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.public_id), '[]'::jsonb)
    INTO v_result
    FROM (
        SELECT
            public_id,
            username,
            display_name,
            COALESCE(account_level,1) AS account_level
        FROM public.profiles
        WHERE public_id IS NOT NULL
          AND (
                v_q = ''
                OR public_id::text = regexp_replace(v_q,'[^0-9]','','g')
                OR COALESCE(display_name,'') ILIKE '%' || v_q || '%'
                OR COALESCE(username,'') ILIKE '%' || v_q || '%'
          )
        ORDER BY public_id
        LIMIT 200
    ) x;

    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_user_details(
    p_token text,
    p_public_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
    v_target public.profiles%ROWTYPE;
    v_daily numeric := 0;
    v_has_counter boolean := false;
BEGIN
    IF NOT public.zono__developer_console_session_ok(p_token) THEN
        RAISE EXCEPTION 'INVALID_CONSOLE_SESSION';
    END IF;

    SELECT *
    INTO v_target
    FROM public.profiles
    WHERE public_id = p_public_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'USER_NOT_FOUND';
    END IF;

    -- قيمة يومية احتياطية حسب رتبة العداد الحالية
    v_daily := CASE COALESCE(v_target.active_bird_rank,0)
        WHEN 1 THEN 500
        WHEN 2 THEN 750
        WHEN 3 THEN 1000
        WHEN 4 THEN 1500
        WHEN 5 THEN 2500
        ELSE 0
    END;

    v_has_counter :=
        COALESCE(v_target.active_bird_rank,0) > 0
        OR (
            v_target.bird_plan_ends_at IS NOT NULL
            AND v_target.bird_plan_ends_at > now()
        );

    RETURN jsonb_build_object(
        'public_id', v_target.public_id,
        'username', v_target.username,
        'display_name', v_target.display_name,
        'account_level', COALESCE(v_target.account_level,1),
        'seeds', COALESCE(v_target.seeds,0),
        'feathers', COALESCE(v_target.feathers,0),
        'daily_seeds', COALESCE(v_daily,0),
        'has_counter', v_has_counter,
        'active_bird_rank', COALESCE(v_target.active_bird_rank,0),
        'active_bird', v_target.active_bird,
        'bird_plan_ends_at', v_target.bird_plan_ends_at
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_developer_zero_user_seeds(
    p_token text,
    p_public_id bigint
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
    v_target_id uuid;
    v_before bigint;
BEGIN
    IF NOT public.zono__developer_console_session_ok(p_token) THEN
        RAISE EXCEPTION 'INVALID_CONSOLE_SESSION';
    END IF;

    SELECT id, COALESCE(seeds,0)::bigint
    INTO v_target_id, v_before
    FROM public.profiles
    WHERE public_id = p_public_id
    FOR UPDATE;

    IF v_target_id IS NULL THEN
        RAISE EXCEPTION 'USER_NOT_FOUND';
    END IF;

    UPDATE public.profiles
    SET seeds = 0
    WHERE id = v_target_id;

    INSERT INTO public.zono_developer_console_audit(
        developer_id,
        target_user_id,
        target_public_id,
        action,
        before_data,
        after_data
    )
    VALUES (
        auth.uid(),
        v_target_id,
        p_public_id,
        'zero_seeds',
        jsonb_build_object('seeds',v_before),
        jsonb_build_object('seeds',0)
    );

    RETURN jsonb_build_object(
        'ok',true,
        'public_id',p_public_id,
        'previous_seeds',v_before,
        'seeds',0
    );
END;
$$;

REVOKE ALL ON FUNCTION public.zono__developer_console_session_ok(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.zono_developer_query_users(text,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_developer_user_details(text,bigint) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_developer_zero_user_seeds(text,bigint) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.zono_developer_query_users(text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_developer_user_details(text,bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_developer_zero_user_seeds(text,bigint) TO authenticated;

NOTIFY pgrst, 'reload schema';
SELECT pg_notify('pgrst', 'reload schema');

SELECT
    n.nspname AS schema_name,
    p.proname AS function_name,
    pg_get_function_identity_arguments(p.oid) AS arguments
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
  AND p.proname IN (
      'zono_developer_query_users',
      'zono_developer_user_details',
      'zono_developer_zero_user_seeds'
  )
ORDER BY p.proname;
