-- =============================================================
-- ZONO 24.0 — الإدارة: الحوالات + طلبات الوكلاء
-- نفّذ الملف كاملاً مرة واحدة في Supabase SQL Editor.
-- =============================================================

-- حقول اعتماد الوكيل
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS agent_verified boolean NOT NULL DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS agent_since timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS agent_previous_public_id bigint;

-- -------------------------------------------------------------
-- 1) حوالات / سحوبات البذور (V2)
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.zono_withdrawal_requests_v2 (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    public_id_snapshot bigint NOT NULL,
    display_name_snapshot text,
    method text NOT NULL CHECK (method IN ('fib','qi')),
    account_name text NOT NULL,
    fib_phone text,
    qi_phone_11 text,
    qi_account text,
    amount_seeds bigint NOT NULL CHECK (amount_seeds > 0),
    amount_iqd bigint NOT NULL CHECK (amount_iqd >= 0),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
    rejection_reason text,
    reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS zono_withdrawal_requests_v2_user_idx
    ON public.zono_withdrawal_requests_v2(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS zono_withdrawal_requests_v2_status_idx
    ON public.zono_withdrawal_requests_v2(status, created_at ASC);

ALTER TABLE public.zono_withdrawal_requests_v2 ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.zono_withdrawal_requests_v2 FROM anon, authenticated;

-- -------------------------------------------------------------
-- 2) طلبات الوكالة
-- -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.zono_agency_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    public_id_at_request bigint NOT NULL,
    display_name_at_request text,
    fee_seeds bigint NOT NULL DEFAULT 1000 CHECK (fee_seeds > 0),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
    assigned_public_id bigint,
    rejection_reason text,
    reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    reviewed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS zono_agency_requests_user_idx
    ON public.zono_agency_requests(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS zono_agency_requests_status_idx
    ON public.zono_agency_requests(status, created_at ASC);

ALTER TABLE public.zono_agency_requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.zono_agency_requests FROM anon, authenticated;

-- -------------------------------------------------------------
-- Helpers
-- -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.zono__require_developer_v2()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_role text;
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'NOT_AUTHENTICATED';
    END IF;

    SELECT role INTO v_role
    FROM public.profiles
    WHERE id = auth.uid();

    IF COALESCE(v_role,'') <> 'developer' THEN
        RAISE EXCEPTION 'DEVELOPER_ONLY';
    END IF;
END;
$$;

-- -------------------------------------------------------------
-- Withdrawal: create request + deduct seeds immediately
-- -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.zono_withdrawal_submit_v2(
    p_method text,
    p_account_name text,
    p_fib_phone text,
    p_qi_phone_11 text,
    p_qi_account text,
    p_amount_seeds bigint,
    p_verification_code text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_profile public.profiles%ROWTYPE;
    v_id bigint;
    v_method text := lower(btrim(COALESCE(p_method,'')));
    v_account_name text := btrim(COALESCE(p_account_name,''));
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;

    SELECT * INTO v_profile
    FROM public.profiles
    WHERE id = auth.uid()
    FOR UPDATE;

    IF NOT FOUND THEN RAISE EXCEPTION 'PROFILE_NOT_FOUND'; END IF;
    -- جميع المستخدمين المسجلين يمكنهم تقديم طلب سحب؛ صلاحية المطور مطلوبة فقط لمعالجة الطلب.
    IF v_method NOT IN ('fib','qi') THEN RAISE EXCEPTION 'INVALID_METHOD'; END IF;
    IF char_length(v_account_name) < 2 THEN RAISE EXCEPTION 'INVALID_ACCOUNT_NAME'; END IF;
    IF p_amount_seeds IS NULL OR p_amount_seeds < 15000 THEN RAISE EXCEPTION 'MIN_WITHDRAWAL_15000'; END IF;
    IF COALESCE(v_profile.seeds,0) < p_amount_seeds THEN RAISE EXCEPTION 'INSUFFICIENT_SEEDS'; END IF;
    IF char_length(COALESCE(p_verification_code,'')) < 4 OR char_length(COALESCE(p_verification_code,'')) > 8 THEN
        RAISE EXCEPTION 'INVALID_VERIFICATION_CODE';
    END IF;

    IF v_method = 'fib' THEN
        IF char_length(regexp_replace(COALESCE(p_fib_phone,''),'[^0-9]','','g')) < 10 THEN RAISE EXCEPTION 'INVALID_FIB_PHONE'; END IF;
    ELSE
        IF char_length(regexp_replace(COALESCE(p_qi_phone_11,''),'[^0-9]','','g')) <> 11 THEN RAISE EXCEPTION 'INVALID_QI_PHONE'; END IF;
        IF char_length(regexp_replace(COALESCE(p_qi_account,''),'[^0-9]','','g')) < 4 THEN RAISE EXCEPTION 'INVALID_QI_ACCOUNT'; END IF;
    END IF;

    UPDATE public.profiles
    SET seeds = COALESCE(seeds,0) - p_amount_seeds
    WHERE id = auth.uid();

    INSERT INTO public.zono_withdrawal_requests_v2(
        user_id, public_id_snapshot, display_name_snapshot, method, account_name,
        fib_phone, qi_phone_11, qi_account, amount_seeds, amount_iqd
    ) VALUES (
        auth.uid(), v_profile.public_id, v_profile.display_name, v_method, v_account_name,
        NULLIF(btrim(COALESCE(p_fib_phone,'')),''),
        NULLIF(btrim(COALESCE(p_qi_phone_11,'')),''),
        NULLIF(btrim(COALESCE(p_qi_account,'')),''),
        p_amount_seeds, p_amount_seeds
    ) RETURNING id INTO v_id;

    INSERT INTO public.zono_notifications(user_id, kind, title, body, sender_public_id, amount, is_read, created_at)
    VALUES (
        auth.uid(), 'withdrawal_status', 'طلب سحب قيد المعالجة',
        'تم خصم ' || p_amount_seeds || ' بذرة وحجزها حتى مراجعة الإدارة.',
        NULL, p_amount_seeds, false, now()
    );

    RETURN jsonb_build_object('ok',true,'id',v_id,'status','pending','amount_seeds',p_amount_seeds);
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_withdrawal_my_v2()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE v_result jsonb;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
    SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.created_at DESC),'[]'::jsonb)
    INTO v_result
    FROM (
        SELECT id, method, amount_seeds, amount_iqd, status, rejection_reason, created_at, reviewed_at
        FROM public.zono_withdrawal_requests_v2
        WHERE user_id = auth.uid()
        ORDER BY created_at DESC
        LIMIT 100
    ) x;
    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_withdrawal_pending_v2()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE v_result jsonb;
BEGIN
    PERFORM public.zono__require_developer_v2();
    SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.created_at ASC),'[]'::jsonb)
    INTO v_result
    FROM (
        SELECT id, public_id_snapshot AS public_id, display_name_snapshot AS display_name,
               method, account_name, fib_phone, qi_phone_11, qi_account,
               amount_seeds, amount_iqd, created_at
        FROM public.zono_withdrawal_requests_v2
        WHERE status = 'pending'
        ORDER BY created_at ASC
    ) x;
    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_withdrawal_approved_v2()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE v_result jsonb;
BEGIN
    PERFORM public.zono__require_developer_v2();
    SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.reviewed_at DESC),'[]'::jsonb)
    INTO v_result
    FROM (
        SELECT id, public_id_snapshot AS public_id, display_name_snapshot AS display_name,
               account_name, amount_seeds, amount_iqd, method, reviewed_at
        FROM public.zono_withdrawal_requests_v2
        WHERE status = 'approved'
        ORDER BY reviewed_at DESC NULLS LAST
        LIMIT 200
    ) x;
    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_withdrawal_review_v2(
    p_withdrawal_id bigint,
    p_decision text,
    p_rejection_reason text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_req public.zono_withdrawal_requests_v2%ROWTYPE;
    v_decision text := lower(btrim(COALESCE(p_decision,'')));
    v_reason text := NULLIF(btrim(COALESCE(p_rejection_reason,'')),'');
BEGIN
    PERFORM public.zono__require_developer_v2();
    IF v_decision NOT IN ('approved','rejected') THEN RAISE EXCEPTION 'INVALID_DECISION'; END IF;
    IF v_decision = 'rejected' AND char_length(COALESCE(v_reason,'')) < 3 THEN RAISE EXCEPTION 'REJECTION_REASON_REQUIRED'; END IF;

    SELECT * INTO v_req
    FROM public.zono_withdrawal_requests_v2
    WHERE id = p_withdrawal_id
    FOR UPDATE;

    IF NOT FOUND THEN RAISE EXCEPTION 'REQUEST_NOT_FOUND'; END IF;
    IF v_req.status <> 'pending' THEN RAISE EXCEPTION 'REQUEST_NOT_PENDING'; END IF;

    IF v_decision = 'rejected' THEN
        UPDATE public.profiles
        SET seeds = COALESCE(seeds,0) + v_req.amount_seeds
        WHERE id = v_req.user_id;
    END IF;

    UPDATE public.zono_withdrawal_requests_v2
    SET status = v_decision,
        rejection_reason = CASE WHEN v_decision='rejected' THEN left(v_reason,300) ELSE NULL END,
        reviewed_by = auth.uid(),
        reviewed_at = now()
    WHERE id = v_req.id;

    INSERT INTO public.zono_notifications(user_id, kind, title, body, sender_public_id, amount, is_read, created_at)
    VALUES (
        v_req.user_id,
        'withdrawal_status',
        CASE WHEN v_decision='approved' THEN 'تم قبول طلب السحب' ELSE 'تم رفض طلب السحب' END,
        CASE WHEN v_decision='approved'
            THEN 'تم قبول طلب سحب ' || v_req.amount_seeds || ' بذرة.'
            ELSE 'تم رفض طلب السحب. السبب: ' || left(v_reason,300) || '. وتمت إعادة ' || v_req.amount_seeds || ' بذرة إلى حسابك.' END,
        NULL, v_req.amount_seeds, false, now()
    );

    RETURN jsonb_build_object('ok',true,'status',v_decision,'refunded',v_decision='rejected');
END;
$$;

-- -------------------------------------------------------------
-- Agency: user creates request and 1000 seeds are reserved
-- -------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.zono_agency_create_request()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_profile public.profiles%ROWTYPE;
    v_id bigint;
    v_fee bigint := 1000;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;

    SELECT * INTO v_profile
    FROM public.profiles
    WHERE id = auth.uid()
    FOR UPDATE;

    IF NOT FOUND THEN RAISE EXCEPTION 'PROFILE_NOT_FOUND'; END IF;
    IF COALESCE(v_profile.role,'') IN ('agent','developer') THEN RAISE EXCEPTION 'ALREADY_AGENT'; END IF;
    IF EXISTS (SELECT 1 FROM public.zono_agency_requests WHERE user_id=auth.uid() AND status='pending') THEN
        RAISE EXCEPTION 'PENDING_REQUEST_EXISTS';
    END IF;
    IF COALESCE(v_profile.seeds,0) < v_fee THEN RAISE EXCEPTION 'INSUFFICIENT_SEEDS'; END IF;

    UPDATE public.profiles
    SET seeds = COALESCE(seeds,0) - v_fee
    WHERE id = auth.uid();

    INSERT INTO public.zono_agency_requests(user_id, public_id_at_request, display_name_at_request, fee_seeds)
    VALUES (auth.uid(), v_profile.public_id, v_profile.display_name, v_fee)
    RETURNING id INTO v_id;

    INSERT INTO public.zono_notifications(user_id, kind, title, body, sender_public_id, amount, is_read, created_at)
    VALUES (auth.uid(),'agency_status','طلب وكالة قيد المعالجة','تم حجز 1,000 بذرة حتى مراجعة طلب الوكالة.',NULL,v_fee,false,now());

    RETURN jsonb_build_object('ok',true,'id',v_id,'status','pending','fee_seeds',v_fee);
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_agency_my_requests()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE v_result jsonb;
BEGIN
    IF auth.uid() IS NULL THEN RAISE EXCEPTION 'NOT_AUTHENTICATED'; END IF;
    SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.created_at DESC),'[]'::jsonb)
    INTO v_result
    FROM (
        SELECT id, fee_seeds, status, assigned_public_id, rejection_reason, created_at, reviewed_at
        FROM public.zono_agency_requests
        WHERE user_id = auth.uid()
        ORDER BY created_at DESC
        LIMIT 50
    ) x;
    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_agency_pending_requests()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE v_result jsonb;
BEGIN
    PERFORM public.zono__require_developer_v2();
    SELECT COALESCE(jsonb_agg(to_jsonb(x) ORDER BY x.created_at ASC),'[]'::jsonb)
    INTO v_result
    FROM (
        SELECT a.id, a.user_id, a.public_id_at_request AS public_id,
               a.display_name_at_request AS display_name,
               p.username, a.fee_seeds, a.created_at
        FROM public.zono_agency_requests a
        LEFT JOIN public.profiles p ON p.id = a.user_id
        WHERE a.status='pending'
        ORDER BY a.created_at ASC
    ) x;
    RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.zono_agency_review_request(
    p_request_id bigint,
    p_decision text,
    p_new_public_id bigint DEFAULT NULL,
    p_rejection_reason text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
    v_req public.zono_agency_requests%ROWTYPE;
    v_profile public.profiles%ROWTYPE;
    v_decision text := lower(btrim(COALESCE(p_decision,'')));
    v_reason text := NULLIF(btrim(COALESCE(p_rejection_reason,'')),'');
BEGIN
    PERFORM public.zono__require_developer_v2();
    IF v_decision NOT IN ('approved','rejected') THEN RAISE EXCEPTION 'INVALID_DECISION'; END IF;

    SELECT * INTO v_req
    FROM public.zono_agency_requests
    WHERE id = p_request_id
    FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'REQUEST_NOT_FOUND'; END IF;
    IF v_req.status <> 'pending' THEN RAISE EXCEPTION 'REQUEST_NOT_PENDING'; END IF;

    SELECT * INTO v_profile
    FROM public.profiles
    WHERE id = v_req.user_id
    FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'PROFILE_NOT_FOUND'; END IF;

    IF v_decision = 'approved' THEN
        IF p_new_public_id IS NULL OR p_new_public_id < 1 THEN RAISE EXCEPTION 'NEW_PUBLIC_ID_REQUIRED'; END IF;
        IF EXISTS (SELECT 1 FROM public.profiles WHERE public_id=p_new_public_id AND id<>v_profile.id) THEN
            RAISE EXCEPTION 'PUBLIC_ID_IN_USE';
        END IF;

        UPDATE public.profiles
        SET agent_previous_public_id = v_profile.public_id,
            public_id = p_new_public_id,
            role = 'agent',
            agent_verified = true,
            agent_since = now()
        WHERE id = v_profile.id;

        UPDATE public.zono_agency_requests
        SET status='approved', assigned_public_id=p_new_public_id,
            reviewed_by=auth.uid(), reviewed_at=now(), rejection_reason=NULL
        WHERE id=v_req.id;

        INSERT INTO public.zono_notifications(user_id, kind, title, body, sender_public_id, amount, is_read, created_at)
        VALUES (
            v_req.user_id,'agency_status','تم قبول وكالتك',
            'تم اعتماد حسابك كوكيل معتمد ✓. ID الوكيل الجديد: ' || p_new_public_id || '.',
            NULL,v_req.fee_seeds,false,now()
        );

        RETURN jsonb_build_object('ok',true,'status','approved','new_public_id',p_new_public_id);
    ELSE
        IF char_length(COALESCE(v_reason,'')) < 3 THEN RAISE EXCEPTION 'REJECTION_REASON_REQUIRED'; END IF;

        UPDATE public.profiles
        SET seeds = COALESCE(seeds,0) + v_req.fee_seeds
        WHERE id = v_req.user_id;

        UPDATE public.zono_agency_requests
        SET status='rejected', rejection_reason=left(v_reason,300),
            reviewed_by=auth.uid(), reviewed_at=now()
        WHERE id=v_req.id;

        INSERT INTO public.zono_notifications(user_id, kind, title, body, sender_public_id, amount, is_read, created_at)
        VALUES (
            v_req.user_id,'agency_status','تم رفض طلب الوكالة',
            'تم رفض طلب الوكالة. السبب: ' || left(v_reason,300) || '. وتمت إعادة ' || v_req.fee_seeds || ' بذرة إلى حسابك.',
            NULL,v_req.fee_seeds,false,now()
        );

        RETURN jsonb_build_object('ok',true,'status','rejected','refunded_seeds',v_req.fee_seeds);
    END IF;
END;
$$;

-- -------------------------------------------------------------
-- صلاحيات RPC فقط؛ الجداول نفسها تبقى مغلقة
-- -------------------------------------------------------------
REVOKE ALL ON FUNCTION public.zono_withdrawal_submit_v2(text,text,text,text,text,bigint,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_withdrawal_my_v2() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_withdrawal_pending_v2() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_withdrawal_approved_v2() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_withdrawal_review_v2(bigint,text,text) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_agency_create_request() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_agency_my_requests() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_agency_pending_requests() FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.zono_agency_review_request(bigint,text,bigint,text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.zono_withdrawal_submit_v2(text,text,text,text,text,bigint,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_withdrawal_my_v2() TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_withdrawal_pending_v2() TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_withdrawal_approved_v2() TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_withdrawal_review_v2(bigint,text,text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_agency_create_request() TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_agency_my_requests() TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_agency_pending_requests() TO authenticated;
GRANT EXECUTE ON FUNCTION public.zono_agency_review_request(bigint,text,bigint,text) TO authenticated;

NOTIFY pgrst, 'reload schema';
SELECT pg_notify('pgrst','reload schema');

-- فحص أخير
SELECT n.nspname AS schema_name,
       p.proname AS function_name,
       pg_get_function_identity_arguments(p.oid) AS arguments
FROM pg_proc p
JOIN pg_namespace n ON n.oid=p.pronamespace
WHERE n.nspname='public'
  AND p.proname IN (
    'zono_withdrawal_submit_v2','zono_withdrawal_my_v2','zono_withdrawal_pending_v2',
    'zono_withdrawal_approved_v2','zono_withdrawal_review_v2',
    'zono_agency_create_request','zono_agency_my_requests','zono_agency_pending_requests','zono_agency_review_request'
  )
ORDER BY p.proname;
