-- ZONO - إصلاح إشعارات تحويل البذور فقط
-- شغّل الملف كاملاً مرة واحدة في Supabase SQL Editor.

create table if not exists public.zono_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'general',
  title text not null,
  body text not null,
  sender_public_id bigint,
  amount bigint,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.zono_notifications enable row level security;

drop policy if exists "read own zono notifications" on public.zono_notifications;
create policy "read own zono notifications"
on public.zono_notifications
for select to authenticated
using (user_id = auth.uid());

grant select on public.zono_notifications to authenticated;

-- نحذف النسخة القديمة حتى لا تبقى أسماء باراميترات قديمة في PostgREST.
drop function if exists public.zono_transfer_seeds(bigint,bigint);

create function public.zono_transfer_seeds(
  p_recipient_public_id bigint,
  p_amount bigint
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_sender public.profiles%rowtype;
  v_recipient public.profiles%rowtype;
  v_notification_id bigint;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'عدد البذور غير صحيح'; end if;

  select * into v_sender
  from public.profiles
  where id=auth.uid()
  for update;

  if v_sender.id is null then raise exception 'ملف المرسل غير موجود'; end if;
  if v_sender.role not in ('developer','agent') then
    raise exception 'إرسال البذور متاح للمطور والوكيل فقط';
  end if;

  select * into v_recipient
  from public.profiles
  where public_id=p_recipient_public_id
  for update;

  if v_recipient.id is null then raise exception 'ID المستلم غير موجود'; end if;
  if v_recipient.id=v_sender.id then raise exception 'لا يمكن الإرسال إلى نفس الحساب'; end if;
  if coalesce(v_sender.seeds,0) < p_amount then raise exception 'رصيد البذور غير كافٍ'; end if;

  -- بدون updated_at حتى يعمل حتى لو العمود غير موجود.
  update public.profiles
  set seeds=coalesce(seeds,0)-p_amount
  where id=v_sender.id;

  update public.profiles
  set seeds=coalesce(seeds,0)+p_amount
  where id=v_recipient.id;

  insert into public.zono_notifications
    (user_id,kind,title,body,sender_public_id,amount,is_read)
  values (
    v_recipient.id,
    'seed_transfer',
    'استلام بذور 🌾',
    'استلمت '||p_amount||' بذرة من '||
      coalesce(nullif(v_sender.display_name,''),'مستخدم')||
      ' — ID '||coalesce(v_sender.public_id::text,'-')||
      case
        when v_sender.role='developer' then ' — المطور'
        when v_sender.role='agent' then ' — الوكيل'
        else ''
      end,
    v_sender.public_id,
    p_amount,
    false
  )
  returning id into v_notification_id;

  return jsonb_build_object(
    'ok',true,
    'recipient_id',p_recipient_public_id,
    'amount',p_amount,
    'notification_id',v_notification_id
  );
end;
$$;

drop function if exists public.zono_my_notifications();

create function public.zono_my_notifications()
returns table(
  id bigint,
  kind text,
  title text,
  body text,
  sender_public_id bigint,
  amount bigint,
  is_read boolean,
  created_at timestamptz
)
language sql
security definer
set search_path=public
as $$
  select
    n.id,n.kind,n.title,n.body,n.sender_public_id,
    n.amount,n.is_read,n.created_at
  from public.zono_notifications n
  where n.user_id=auth.uid()
  order by n.id desc
  limit 50;
$$;

drop function if exists public.zono_mark_notifications_read();

create function public.zono_mark_notifications_read()
returns void
language sql
security definer
set search_path=public
as $$
  update public.zono_notifications
  set is_read=true
  where user_id=auth.uid() and is_read=false;
$$;

grant execute on function public.zono_transfer_seeds(bigint,bigint) to authenticated;
grant execute on function public.zono_my_notifications() to authenticated;
grant execute on function public.zono_mark_notifications_read() to authenticated;

notify pgrst,'reload schema';

-- اختبار اختياري بعد إرسال بذور:
-- select id,user_id,kind,body,sender_public_id,amount,is_read,created_at
-- from public.zono_notifications
-- order by id desc
-- limit 10;
