-- ZONO: developer/agent seed transfers + notification bell
-- Run once in Supabase SQL Editor.

alter table public.profiles
  add column if not exists seeds bigint not null default 0 check (seeds >= 0),
  add column if not exists role text not null default 'user';

-- Accepted roles
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check check (role in ('user','agent','developer'));

create table if not exists public.zono_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'general',
  title text not null,
  body text not null,
  sender_public_id bigint,
  amount bigint,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.zono_notifications enable row level security;
drop policy if exists "read own zono notifications" on public.zono_notifications;
create policy "read own zono notifications"
on public.zono_notifications for select to authenticated
using (user_id = auth.uid());

revoke insert, update, delete on public.zono_notifications from anon, authenticated;
grant select on public.zono_notifications to authenticated;

create or replace function public.zono_transfer_seeds(
  p_recipient_public_id bigint,
  p_amount bigint
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_sender public.profiles%rowtype;
  v_recipient public.profiles%rowtype;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'عدد البذور غير صحيح'; end if;

  select * into v_sender from public.profiles where id=auth.uid() for update;
  if v_sender.role not in ('developer','agent') then
    raise exception 'إرسال البذور متاح للمطور والوكيل فقط';
  end if;

  select * into v_recipient from public.profiles where public_id=p_recipient_public_id for update;
  if v_recipient.id is null then raise exception 'ID المستلم غير موجود'; end if;
  if v_recipient.id = v_sender.id then raise exception 'لا يمكن الإرسال إلى نفس الحساب'; end if;
  if coalesce(v_sender.seeds,0) < p_amount then raise exception 'رصيد البذور غير كافٍ'; end if;

  update public.profiles set seeds=seeds-p_amount,updated_at=now() where id=v_sender.id;
  update public.profiles set seeds=seeds+p_amount,updated_at=now() where id=v_recipient.id;

  insert into public.zono_notifications(user_id,kind,title,body,sender_public_id,amount)
  values(
    v_recipient.id,
    'seed_transfer',
    'استلام بذور 🌾',
    'استلمت '||p_amount||' بذرة من '||coalesce(v_sender.display_name,'مستخدم')||
      ' — ID '||v_sender.public_id||
      case when v_sender.role='developer' then ' — المطور' else ' — الوكيل' end,
    v_sender.public_id,
    p_amount
  );

  return jsonb_build_object('ok',true,'recipient_id',p_recipient_public_id,'amount',p_amount);
end;
$$;

create or replace function public.zono_my_notifications()
returns table(
  id bigint, kind text, title text, body text,
  sender_public_id bigint, amount bigint, is_read boolean, created_at timestamptz
)
language sql
security definer
set search_path=public
as $$
  select n.id,n.kind,n.title,n.body,n.sender_public_id,n.amount,n.is_read,n.created_at
  from public.zono_notifications n
  where n.user_id=auth.uid()
  order by n.created_at desc
  limit 50;
$$;

create or replace function public.zono_mark_notifications_read()
returns void
language sql
security definer
set search_path=public
as $$
  update public.zono_notifications set is_read=true
  where user_id=auth.uid() and is_read=false;
$$;

-- Use this RPC later when private messages are stored in Supabase.
create or replace function public.zono_notify_private_message(
  p_recipient_public_id bigint,
  p_preview text
) returns void
language plpgsql
security definer
set search_path=public
as $$
declare
  v_sender public.profiles%rowtype;
  v_recipient public.profiles%rowtype;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
  select * into v_sender from public.profiles where id=auth.uid();
  select * into v_recipient from public.profiles where public_id=p_recipient_public_id;
  if v_recipient.id is null then raise exception 'ID المستلم غير موجود'; end if;

  insert into public.zono_notifications(user_id,kind,title,body,sender_public_id)
  values(v_recipient.id,'private_message','رسالة خاصة جديدة 💬',
         coalesce(v_sender.display_name,'مستخدم')||' — ID '||v_sender.public_id||': '||
         left(coalesce(p_preview,''),80),v_sender.public_id);
end;
$$;

grant execute on function public.zono_transfer_seeds(bigint,bigint) to authenticated;
grant execute on function public.zono_my_notifications() to authenticated;
grant execute on function public.zono_mark_notifications_read() to authenticated;
grant execute on function public.zono_notify_private_message(bigint,text) to authenticated;

notify pgrst,'reload schema';

-- To promote a user to agent:
-- update public.profiles set role='agent' where public_id=123;
