-- ZONO REAL ROOMS + MODERATION + GIFTS
-- Run ONCE in Supabase SQL Editor.
-- Room creation: 30,000 seeds.
-- Public room IDs start at 50 and never reuse deleted IDs.
-- Rose gift: 100 feathers. Split = 20% company / 20% room owner / 60% recipient.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------
-- Room IDs start at 50
-- ---------------------------------------------------------
create sequence if not exists public.zono_room_public_id_seq
  as bigint
  start with 50
  increment by 1
  minvalue 50
  no cycle;

create table if not exists public.zono_rooms (
  id bigint generated by default as identity primary key,
  public_id bigint not null unique default nextval('public.zono_room_public_id_seq'),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  bio text not null,
  image_url text not null,
  is_locked boolean not null default false,
  password_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.zono_room_moderators (
  room_id bigint not null references public.zono_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(room_id,user_id)
);

create table if not exists public.zono_room_restrictions (
  room_id bigint not null references public.zono_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  banned boolean not null default false,
  muted_permanent boolean not null default false,
  muted_until timestamptz,
  kicked_until timestamptz,
  updated_at timestamptz not null default now(),
  primary key(room_id,user_id)
);

create table if not exists public.zono_room_presence (
  room_id bigint not null references public.zono_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key(room_id,user_id)
);

create table if not exists public.zono_room_messages (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.zono_rooms(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  message_type text not null default 'text' check(message_type in ('text','gift','system')),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.zono_room_gifts (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.zono_rooms(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid references public.profiles(id) on delete set null,
  to_all boolean not null default false,
  gift_key text not null,
  unit_price bigint not null,
  recipient_count integer not null,
  total_cost bigint not null,
  company_share bigint not null,
  owner_share bigint not null,
  recipients_share bigint not null,
  created_at timestamptz not null default now()
);

create table if not exists public.zono_company_wallet (
  singleton boolean primary key default true check(singleton),
  feathers_balance bigint not null default 0,
  updated_at timestamptz not null default now()
);
insert into public.zono_company_wallet(singleton,feathers_balance)
values(true,0) on conflict(singleton) do nothing;

-- no direct table access from clients; access goes through RPCs
alter table public.zono_rooms enable row level security;
alter table public.zono_room_moderators enable row level security;
alter table public.zono_room_restrictions enable row level security;
alter table public.zono_room_presence enable row level security;
alter table public.zono_room_messages enable row level security;
alter table public.zono_room_gifts enable row level security;
alter table public.zono_company_wallet enable row level security;

revoke all on public.zono_rooms from anon,authenticated;
revoke all on public.zono_room_moderators from anon,authenticated;
revoke all on public.zono_room_restrictions from anon,authenticated;
revoke all on public.zono_room_presence from anon,authenticated;
revoke all on public.zono_room_messages from anon,authenticated;
revoke all on public.zono_room_gifts from anon,authenticated;
revoke all on public.zono_company_wallet from anon,authenticated;

-- ---------------------------------------------------------
-- Storage bucket for room images
-- ---------------------------------------------------------
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('room-images','room-images',true,3145728,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update
set public=true,file_size_limit=3145728,allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "zono_room_images_auth_insert" on storage.objects;
create policy "zono_room_images_auth_insert"
on storage.objects for insert to authenticated
with check(bucket_id='room-images' and (storage.foldername(name))[1]=auth.uid()::text);

drop policy if exists "zono_room_images_public_read" on storage.objects;
create policy "zono_room_images_public_read"
on storage.objects for select to public
using(bucket_id='room-images');

-- ---------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------
create or replace function public.zono_room_is_staff(p_room_id bigint,p_user_id uuid)
returns boolean language sql stable security definer set search_path=public
as $$
  select exists(select 1 from public.zono_rooms r where r.id=p_room_id and r.owner_id=p_user_id)
      or exists(select 1 from public.zono_room_moderators m where m.room_id=p_room_id and m.user_id=p_user_id);
$$;

create or replace function public.zono_room_is_muted(p_room_id bigint,p_user_id uuid)
returns boolean language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.zono_room_restrictions x
    where x.room_id=p_room_id and x.user_id=p_user_id
      and (x.muted_permanent=true or (x.muted_until is not null and x.muted_until>now()))
  );
$$;

-- ---------------------------------------------------------
-- Create room — deduct exactly 30,000 seeds atomically
-- ---------------------------------------------------------
create or replace function public.zono_create_room(p_name text,p_bio text,p_image_url text)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_profile public.profiles%rowtype; v_room public.zono_rooms%rowtype;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
  if length(trim(coalesce(p_name,'')))<2 or length(trim(p_name))>60 then raise exception 'اسم الروم غير صحيح'; end if;
  if length(trim(coalesce(p_bio,'')))<2 or length(trim(p_bio))>240 then raise exception 'نبذة الروم غير صحيحة'; end if;
  if length(trim(coalesce(p_image_url,'')))<8 then raise exception 'صورة الروم مطلوبة'; end if;

  select * into v_profile from public.profiles where id=auth.uid() for update;
  if v_profile.id is null then raise exception 'الحساب غير موجود'; end if;
  if coalesce(v_profile.seeds,0)<30000 then raise exception 'تحتاج 30000 بذرة لإنشاء روم'; end if;

  update public.profiles set seeds=coalesce(seeds,0)-30000 where id=auth.uid();

  insert into public.zono_rooms(owner_id,name,bio,image_url)
  values(auth.uid(),trim(p_name),trim(p_bio),trim(p_image_url))
  returning * into v_room;

  return jsonb_build_object('ok',true,'public_id',v_room.public_id,'room_id',v_room.id);
end $$;
grant execute on function public.zono_create_room(text,text,text) to authenticated;

-- ---------------------------------------------------------
-- Room listing
-- ---------------------------------------------------------
create or replace function public.zono_list_rooms()
returns table(
  public_id bigint,name text,bio text,image_url text,is_locked boolean,
  owner_public_id bigint,owner_name text,active_members bigint,created_at timestamptz
)
language sql security definer set search_path=public
as $$
  select r.public_id,r.name,r.bio,r.image_url,r.is_locked,
         p.public_id,p.display_name,
         (select count(*) from public.zono_room_presence pr
          where pr.room_id=r.id and pr.last_seen_at>now()-interval '45 seconds') as active_members,
         r.created_at
  from public.zono_rooms r
  join public.profiles p on p.id=r.owner_id
  order by r.created_at desc;
$$;
grant execute on function public.zono_list_rooms() to authenticated;

-- ---------------------------------------------------------
-- Enter room
-- ---------------------------------------------------------
create or replace function public.zono_enter_room(p_room_public_id bigint,p_password text default null)
returns jsonb language plpgsql security definer set search_path=public,extensions
as $$
declare v_room public.zono_rooms%rowtype; v_restrict public.zono_room_restrictions%rowtype;
        v_owner boolean; v_mod boolean; v_count bigint;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;

  select * into v_room from public.zono_rooms where public_id=p_room_public_id;
  if v_room.id is null then raise exception 'الروم غير موجود'; end if;

  select * into v_restrict from public.zono_room_restrictions
  where room_id=v_room.id and user_id=auth.uid();

  if coalesce(v_restrict.banned,false) then raise exception 'ROOM_BANNED'; end if;
  if v_restrict.kicked_until is not null and v_restrict.kicked_until>now() then raise exception 'ROOM_KICKED'; end if;

  v_owner := v_room.owner_id=auth.uid();
  v_mod := exists(select 1 from public.zono_room_moderators where room_id=v_room.id and user_id=auth.uid());

  if v_room.is_locked and not(v_owner or v_mod) then
    if p_password is null or p_password='' then raise exception 'ROOM_PASSWORD_REQUIRED'; end if;
    if v_room.password_hash is null
       or extensions.crypt(p_password,v_room.password_hash)<>v_room.password_hash
    then raise exception 'ROOM_PASSWORD_INVALID'; end if;
  end if;

  insert into public.zono_room_presence(room_id,user_id,joined_at,last_seen_at)
  values(v_room.id,auth.uid(),now(),now())
  on conflict(room_id,user_id) do update set last_seen_at=now();

  select count(*) into v_count from public.zono_room_presence
  where room_id=v_room.id and last_seen_at>now()-interval '45 seconds';

  return jsonb_build_object(
    'ok',true,'public_id',v_room.public_id,'name',v_room.name,'bio',v_room.bio,
    'image_url',v_room.image_url,'is_locked',v_room.is_locked,
    'is_owner',v_owner,'is_moderator',v_mod,'active_members',v_count
  );
end $$;
grant execute on function public.zono_enter_room(bigint,text) to authenticated;

create or replace function public.zono_room_heartbeat(p_room_public_id bigint)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_room_id bigint; v_x public.zono_room_restrictions%rowtype;
begin
  select id into v_room_id from public.zono_rooms where public_id=p_room_public_id;
  if v_room_id is null then return jsonb_build_object('allowed',false,'reason','تم حذف الروم'); end if;

  select * into v_x from public.zono_room_restrictions where room_id=v_room_id and user_id=auth.uid();
  if coalesce(v_x.banned,false) then return jsonb_build_object('allowed',false,'reason','أنت محظور من هذا الروم'); end if;
  if v_x.kicked_until is not null and v_x.kicked_until>now() then return jsonb_build_object('allowed',false,'reason','تم طردك من الروم'); end if;

  update public.zono_room_presence set last_seen_at=now()
  where room_id=v_room_id and user_id=auth.uid();

  if not found then
    insert into public.zono_room_presence(room_id,user_id) values(v_room_id,auth.uid());
  end if;

  return jsonb_build_object('allowed',true);
end $$;
grant execute on function public.zono_room_heartbeat(bigint) to authenticated;

create or replace function public.zono_leave_room(p_room_public_id bigint)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_room_id bigint;
begin
  select id into v_room_id from public.zono_rooms where public_id=p_room_public_id;
  if v_room_id is not null then
    delete from public.zono_room_presence where room_id=v_room_id and user_id=auth.uid();
  end if;
  return jsonb_build_object('ok',true);
end $$;
grant execute on function public.zono_leave_room(bigint) to authenticated;

-- ---------------------------------------------------------
-- Public messages
-- ---------------------------------------------------------
create or replace function public.zono_room_messages(p_room_public_id bigint)
returns table(
  id bigint,message_type text,content text,created_at timestamptz,
  sender_public_id bigint,sender_name text,sender_avatar text,name_theme text,avatar_frame text
)
language sql security definer set search_path=public
as $$
  select m.id,m.message_type,m.content,m.created_at,
         p.public_id,p.display_name,p.avatar_url,
         coalesce(p.active_name_theme,'basic'),
         coalesce(p.active_avatar_frame,'frame_basic')
  from public.zono_room_messages m
  join public.zono_rooms r on r.id=m.room_id
  left join public.profiles p on p.id=m.sender_id
  where r.public_id=p_room_public_id
  order by m.id desc
  limit 150;
$$;
grant execute on function public.zono_room_messages(bigint) to authenticated;

-- Since query above is DESC for efficient limit, expose ordered wrapper
create or replace function public.zono_send_room_message(p_room_public_id bigint,p_message text)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_room_id bigint; v_x public.zono_room_restrictions%rowtype;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
  if length(trim(coalesce(p_message,'')))<1 or length(p_message)>1000 then raise exception 'الرسالة غير صالحة'; end if;

  select id into v_room_id from public.zono_rooms where public_id=p_room_public_id;
  if v_room_id is null then raise exception 'الروم غير موجود'; end if;

  if not exists(select 1 from public.zono_room_presence where room_id=v_room_id and user_id=auth.uid() and last_seen_at>now()-interval '2 minutes')
  then raise exception 'يجب دخول الروم أولاً'; end if;

  if public.zono_room_is_muted(v_room_id,auth.uid()) then raise exception 'MUTED'; end if;

  insert into public.zono_room_messages(room_id,sender_id,message_type,content)
  values(v_room_id,auth.uid(),'text',trim(p_message));

  return jsonb_build_object('ok',true);
end $$;
grant execute on function public.zono_send_room_message(bigint,text) to authenticated;

-- ---------------------------------------------------------
-- Active members
-- ---------------------------------------------------------
create or replace function public.zono_room_members(p_room_public_id bigint)
returns table(
  public_id bigint,display_name text,avatar text,is_owner boolean,is_moderator boolean,
  is_muted boolean,is_banned boolean
)
language sql security definer set search_path=public
as $$
  select p.public_id,p.display_name,p.avatar_url,
         (r.owner_id=p.id),
         exists(select 1 from public.zono_room_moderators m where m.room_id=r.id and m.user_id=p.id),
         public.zono_room_is_muted(r.id,p.id),
         coalesce((select x.banned from public.zono_room_restrictions x where x.room_id=r.id and x.user_id=p.id),false)
  from public.zono_rooms r
  join public.zono_room_presence pr on pr.room_id=r.id and pr.last_seen_at>now()-interval '45 seconds'
  join public.profiles p on p.id=pr.user_id
  where r.public_id=p_room_public_id
  order by (r.owner_id=p.id) desc,p.display_name;
$$;
grant execute on function public.zono_room_members(bigint) to authenticated;

-- ---------------------------------------------------------
-- Lock/unlock: owner OR moderator
-- ---------------------------------------------------------
create or replace function public.zono_room_set_lock(p_room_public_id bigint,p_locked boolean,p_password text default null)
returns jsonb language plpgsql security definer set search_path=public,extensions
as $$
declare v_room public.zono_rooms%rowtype;
begin
  select * into v_room from public.zono_rooms where public_id=p_room_public_id;
  if v_room.id is null then raise exception 'الروم غير موجود'; end if;
  if not public.zono_room_is_staff(v_room.id,auth.uid()) then raise exception 'لا تملك صلاحية إدارة الروم'; end if;

  if p_locked then
    if length(coalesce(p_password,''))<4 or length(p_password)>12 then raise exception 'رمز الروم يجب أن يكون من 4 إلى 12 خانة'; end if;
    update public.zono_rooms
    set is_locked=true,password_hash=extensions.crypt(p_password,extensions.gen_salt('bf'))
    where id=v_room.id;
  else
    update public.zono_rooms set is_locked=false,password_hash=null where id=v_room.id;
  end if;

  return jsonb_build_object('ok',true,'is_locked',p_locked);
end $$;
grant execute on function public.zono_room_set_lock(bigint,boolean,text) to authenticated;

-- ---------------------------------------------------------
-- Owner appoints/removes moderators
-- ---------------------------------------------------------
create or replace function public.zono_room_set_moderator(p_room_public_id bigint,p_target_public_id bigint,p_enabled boolean)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_room public.zono_rooms%rowtype; v_target uuid;
begin
  select * into v_room from public.zono_rooms where public_id=p_room_public_id;
  if v_room.id is null then raise exception 'الروم غير موجود'; end if;
  if v_room.owner_id<>auth.uid() then raise exception 'هذه الصلاحية لمالك الروم فقط'; end if;

  select id into v_target from public.profiles where public_id=p_target_public_id;
  if v_target is null then raise exception 'المستخدم غير موجود'; end if;
  if v_target=v_room.owner_id then raise exception 'المالك لا يحتاج صلاحية مشرف'; end if;

  if p_enabled then
    insert into public.zono_room_moderators(room_id,user_id) values(v_room.id,v_target)
    on conflict do nothing;
  else
    delete from public.zono_room_moderators where room_id=v_room.id and user_id=v_target;
  end if;

  return jsonb_build_object('ok',true);
end $$;
grant execute on function public.zono_room_set_moderator(bigint,bigint,boolean) to authenticated;

-- ---------------------------------------------------------
-- Moderation: owner or moderators. Cannot moderate owner.
-- clear = remove ban/mute/kick.
-- ---------------------------------------------------------
create or replace function public.zono_room_moderate(
  p_room_public_id bigint,p_target_public_id bigint,p_action text,p_minutes integer default null
)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_room public.zono_rooms%rowtype; v_target uuid; v_is_target_mod boolean;
begin
  select * into v_room from public.zono_rooms where public_id=p_room_public_id;
  if v_room.id is null then raise exception 'الروم غير موجود'; end if;
  if not public.zono_room_is_staff(v_room.id,auth.uid()) then raise exception 'لا تملك صلاحية الإدارة'; end if;

  select id into v_target from public.profiles where public_id=p_target_public_id;
  if v_target is null then raise exception 'المستخدم غير موجود'; end if;
  if v_target=v_room.owner_id then raise exception 'لا يمكن اتخاذ إجراء ضد مالك الروم'; end if;

  v_is_target_mod := exists(select 1 from public.zono_room_moderators where room_id=v_room.id and user_id=v_target);
  if v_is_target_mod and v_room.owner_id<>auth.uid() then
    raise exception 'المشرف لا يستطيع اتخاذ إجراء ضد مشرف آخر';
  end if;

  insert into public.zono_room_restrictions(room_id,user_id)
  values(v_room.id,v_target)
  on conflict(room_id,user_id) do nothing;

  if p_action='kick' then
    update public.zono_room_restrictions set kicked_until=now()+interval '15 seconds',updated_at=now()
    where room_id=v_room.id and user_id=v_target;
    delete from public.zono_room_presence where room_id=v_room.id and user_id=v_target;

  elsif p_action='ban' then
    update public.zono_room_restrictions set banned=true,updated_at=now()
    where room_id=v_room.id and user_id=v_target;
    delete from public.zono_room_presence where room_id=v_room.id and user_id=v_target;

  elsif p_action='mute_temp' then
    update public.zono_room_restrictions
    set muted_permanent=false,muted_until=now()+make_interval(mins=>greatest(1,least(coalesce(p_minutes,30),10080))),updated_at=now()
    where room_id=v_room.id and user_id=v_target;

  elsif p_action='mute_perm' then
    update public.zono_room_restrictions set muted_permanent=true,muted_until=null,updated_at=now()
    where room_id=v_room.id and user_id=v_target;

  elsif p_action='clear' then
    update public.zono_room_restrictions
    set banned=false,muted_permanent=false,muted_until=null,kicked_until=null,updated_at=now()
    where room_id=v_room.id and user_id=v_target;

  else raise exception 'إجراء غير معروف';
  end if;

  return jsonb_build_object('ok',true);
end $$;
grant execute on function public.zono_room_moderate(bigint,bigint,text,integer) to authenticated;

-- ---------------------------------------------------------
-- Delete room: OWNER ONLY. No seed refund. public_id never reused.
-- ---------------------------------------------------------
create or replace function public.zono_delete_room(p_room_public_id bigint)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare v_room public.zono_rooms%rowtype;
begin
  select * into v_room from public.zono_rooms where public_id=p_room_public_id for update;
  if v_room.id is null then raise exception 'الروم غير موجود'; end if;
  if v_room.owner_id<>auth.uid() then raise exception 'حذف الروم متاح للمالك فقط'; end if;

  delete from public.zono_rooms where id=v_room.id;
  return jsonb_build_object('ok',true,'deleted_public_id',v_room.public_id,'refunded_seeds',0);
end $$;
grant execute on function public.zono_delete_room(bigint) to authenticated;

-- ---------------------------------------------------------
-- Gifts
-- Rose = 100 feathers per recipient.
-- 20 company / 20 room owner / 60 recipient.
-- To-all charges 100 for every other active member.
-- ---------------------------------------------------------
create or replace function public.zono_send_room_gift(
  p_room_public_id bigint,
  p_recipient_public_id bigint default null,
  p_to_all boolean default false,
  p_gift_key text default 'rose'
)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare
  v_room public.zono_rooms%rowtype;
  v_sender public.profiles%rowtype;
  v_recipient uuid;
  v_recipient_name text;
  v_count integer;
  v_total bigint;
  v_company bigint;
  v_owner bigint;
  v_recipients bigint;
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
  if p_gift_key<>'rose' then raise exception 'هذه الهدية قريبًا'; end if;

  select * into v_room from public.zono_rooms where public_id=p_room_public_id;
  if v_room.id is null then raise exception 'الروم غير موجود'; end if;

  select * into v_sender from public.profiles where id=auth.uid() for update;
  if v_sender.id is null then raise exception 'الحساب غير موجود'; end if;

  if p_to_all then
    select count(*)::integer into v_count
    from public.zono_room_presence pr
    where pr.room_id=v_room.id
      and pr.last_seen_at>now()-interval '45 seconds'
      and pr.user_id<>auth.uid();

    if v_count<1 then raise exception 'لا يوجد مستلمون آخرون في الروم'; end if;
  else
    select p.id,p.display_name into v_recipient,v_recipient_name
    from public.profiles p
    join public.zono_room_presence pr on pr.user_id=p.id
    where p.public_id=p_recipient_public_id
      and pr.room_id=v_room.id
      and pr.last_seen_at>now()-interval '45 seconds';

    if v_recipient is null then raise exception 'المستلم غير موجود في الروم'; end if;
    if v_recipient=auth.uid() then raise exception 'لا يمكنك إرسال هدية لنفسك'; end if;
    v_count:=1;
  end if;

  v_total:=100*v_count;
  if coalesce(v_sender.feathers,0)<v_total then raise exception 'رصيد الريش غير كافٍ'; end if;

  v_company:=20*v_count;
  v_owner:=20*v_count;
  v_recipients:=60*v_count;

  -- sender pays full price
  update public.profiles set feathers=coalesce(feathers,0)-v_total where id=auth.uid();

  -- company 20%
  update public.zono_company_wallet
  set feathers_balance=feathers_balance+v_company,updated_at=now()
  where singleton=true;

  -- room owner 20%
  update public.profiles set feathers=coalesce(feathers,0)+v_owner where id=v_room.owner_id;

  -- recipients 60%
  if p_to_all then
    update public.profiles p
    set feathers=coalesce(p.feathers,0)+60
    where p.id in (
      select pr.user_id from public.zono_room_presence pr
      where pr.room_id=v_room.id
        and pr.last_seen_at>now()-interval '45 seconds'
        and pr.user_id<>auth.uid()
    );
  else
    update public.profiles set feathers=coalesce(feathers,0)+60 where id=v_recipient;
  end if;

  insert into public.zono_room_gifts(
    room_id,sender_id,recipient_id,to_all,gift_key,unit_price,recipient_count,total_cost,
    company_share,owner_share,recipients_share
  ) values(
    v_room.id,auth.uid(),case when p_to_all then null else v_recipient end,p_to_all,'rose',100,v_count,v_total,
    v_company,v_owner,v_recipients
  );

  insert into public.zono_room_messages(room_id,sender_id,message_type,content)
  values(
    v_room.id,auth.uid(),'gift',
    case when p_to_all
      then 'أرسل وردة 🌹 إلى الجميع'
      else 'أرسل وردة 🌹 إلى '||coalesce(v_recipient_name,'المستخدم')
    end
  );

  return jsonb_build_object(
    'ok',true,'recipient_count',v_count,'total_cost',v_total,
    'company_share',v_company,'owner_share',v_owner,'recipients_share',v_recipients
  );
end $$;
grant execute on function public.zono_send_room_gift(bigint,bigint,boolean,text) to authenticated;

notify pgrst,'reload schema';
