-- ZONO WALLET WITHDRAWALS
-- Run once in Supabase SQL Editor.

create table if not exists public.zono_withdrawals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  public_id bigint not null,
  method text not null check (method in ('fib','qi')),
  account_name text not null,
  fib_phone text,
  qi_phone_11 text,
  qi_account text,
  amount_seeds bigint not null check (amount_seeds >= 15000),
  amount_iqd bigint not null check (amount_iqd >= 15000),
  verification_code text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  rejection_reason text,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.zono_withdrawals enable row level security;

drop policy if exists "withdrawals_read_own" on public.zono_withdrawals;
create policy "withdrawals_read_own"
on public.zono_withdrawals
for select
to authenticated
using (user_id = auth.uid());

revoke all on public.zono_withdrawals from anon, authenticated;

-- ---------------------------------------------------------
-- Create request: deduct seeds immediately.
-- ---------------------------------------------------------
drop function if exists public.zono_create_withdrawal(text,text,text,text,text,bigint,text);

create function public.zono_create_withdrawal(
  p_method text,
  p_account_name text,
  p_fib_phone text,
  p_qi_phone_11 text,
  p_qi_account text,
  p_amount_seeds bigint,
  p_verification_code text
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_profile public.profiles%rowtype;
  v_id bigint;
begin
  if auth.uid() is null then
    raise exception 'يجب تسجيل الدخول';
  end if;

  if p_method not in ('fib','qi') then
    raise exception 'طريقة السحب غير صحيحة';
  end if;

  if length(trim(coalesce(p_account_name,''))) < 2 then
    raise exception 'اسم صاحب الحساب مطلوب';
  end if;

  if p_amount_seeds is null or p_amount_seeds < 15000 then
    raise exception 'الحد الأدنى للسحب 15000 بذرة';
  end if;

  if coalesce(p_verification_code,'') !~ '^[0-9]{4,8}$' then
    raise exception 'رمز التوثيق يجب أن يكون من 4 إلى 8 أرقام';
  end if;

  if p_method = 'fib' then
    if coalesce(p_fib_phone,'') !~ '^[0-9]{10,15}$' then
      raise exception 'رقم هاتف FIB غير صحيح';
    end if;
  else
    if coalesce(p_qi_phone_11,'') !~ '^[0-9]{11}$' then
      raise exception 'يجب أن يكون رقم Qi مكوناً من 11 رقم';
    end if;
    if coalesce(p_qi_account,'') !~ '^[0-9]{4,30}$' then
      raise exception 'رقم حساب Qi غير صحيح';
    end if;
  end if;

  select * into v_profile
  from public.profiles
  where id = auth.uid()
  for update;

  if v_profile.id is null then
    raise exception 'ملف المستخدم غير موجود';
  end if;

  if coalesce(v_profile.seeds,0) < p_amount_seeds then
    raise exception 'رصيد البذور غير كافٍ';
  end if;

  update public.profiles
  set seeds = coalesce(seeds,0) - p_amount_seeds
  where id = v_profile.id;

  insert into public.zono_withdrawals(
    user_id, public_id, method, account_name,
    fib_phone, qi_phone_11, qi_account,
    amount_seeds, amount_iqd, verification_code,
    status
  )
  values(
    v_profile.id,
    v_profile.public_id,
    p_method,
    trim(p_account_name),
    case when p_method='fib' then p_fib_phone else null end,
    case when p_method='qi' then p_qi_phone_11 else null end,
    case when p_method='qi' then p_qi_account else null end,
    p_amount_seeds,
    p_amount_seeds,
    p_verification_code,
    'pending'
  )
  returning id into v_id;

  return jsonb_build_object(
    'ok', true,
    'id', v_id,
    'status', 'pending',
    'amount_seeds', p_amount_seeds,
    'amount_iqd', p_amount_seeds
  );
end;
$$;

grant execute on function public.zono_create_withdrawal(text,text,text,text,text,bigint,text) to authenticated;

-- ---------------------------------------------------------
-- User history
-- ---------------------------------------------------------
drop function if exists public.zono_my_withdrawals();

create function public.zono_my_withdrawals()
returns table(
  id bigint,
  method text,
  amount_seeds bigint,
  amount_iqd bigint,
  status text,
  rejection_reason text,
  created_at timestamptz,
  reviewed_at timestamptz
)
language sql
security definer
set search_path=public
as $$
  select
    w.id, w.method, w.amount_seeds, w.amount_iqd,
    w.status, w.rejection_reason, w.created_at, w.reviewed_at
  from public.zono_withdrawals w
  where w.user_id = auth.uid()
  order by w.id desc
  limit 100;
$$;

grant execute on function public.zono_my_withdrawals() to authenticated;

-- ---------------------------------------------------------
-- Developer pending queue
-- ---------------------------------------------------------
drop function if exists public.zono_pending_withdrawals();

create function public.zono_pending_withdrawals()
returns table(
  id bigint,
  public_id bigint,
  method text,
  account_name text,
  fib_phone text,
  qi_phone_11 text,
  qi_account text,
  amount_seeds bigint,
  amount_iqd bigint,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role='developer'
  ) then
    raise exception 'هذه الصفحة للمطور فقط';
  end if;

  return query
  select
    w.id, w.public_id, w.method, w.account_name,
    w.fib_phone, w.qi_phone_11, w.qi_account,
    w.amount_seeds, w.amount_iqd, w.created_at
  from public.zono_withdrawals w
  where w.status='pending'
  order by w.id asc
  limit 100;
end;
$$;

grant execute on function public.zono_pending_withdrawals() to authenticated;

-- ---------------------------------------------------------
-- Approve / reject. Reject refunds all deducted seeds.
-- ---------------------------------------------------------
drop function if exists public.zono_review_withdrawal(bigint,text,text);

create function public.zono_review_withdrawal(
  p_withdrawal_id bigint,
  p_decision text,
  p_rejection_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_row public.zono_withdrawals%rowtype;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id=auth.uid() and p.role='developer'
  ) then
    raise exception 'هذه العملية للمطور فقط';
  end if;

  if p_decision not in ('approved','rejected') then
    raise exception 'قرار غير صحيح';
  end if;

  select * into v_row
  from public.zono_withdrawals
  where id=p_withdrawal_id
  for update;

  if v_row.id is null then
    raise exception 'طلب السحب غير موجود';
  end if;

  if v_row.status <> 'pending' then
    raise exception 'تمت معالجة هذا الطلب مسبقاً';
  end if;

  if p_decision='rejected' and length(trim(coalesce(p_rejection_reason,''))) < 2 then
    raise exception 'يجب كتابة سبب الرفض';
  end if;

  if p_decision='rejected' then
    update public.profiles
    set seeds = coalesce(seeds,0) + v_row.amount_seeds
    where id = v_row.user_id;
  end if;

  update public.zono_withdrawals
  set
    status = p_decision,
    rejection_reason = case when p_decision='rejected' then trim(p_rejection_reason) else null end,
    reviewed_by = auth.uid(),
    reviewed_at = now()
  where id = v_row.id;

  return jsonb_build_object(
    'ok', true,
    'id', v_row.id,
    'status', p_decision,
    'refunded_seeds', case when p_decision='rejected' then v_row.amount_seeds else 0 end
  );
end;
$$;

grant execute on function public.zono_review_withdrawal(bigint,text,text) to authenticated;

notify pgrst,'reload schema';
