-- ZONO - Center refined
-- Run once in Supabase SQL Editor.

-- Counter history: keep only 7 days.
create table if not exists public.zono_activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'activity',
  resource text not null check (resource in ('seed','feather')),
  amount bigint not null default 0,
  title text not null,
  detail text not null default '',
  created_at timestamptz not null default now()
);

alter table public.zono_activity_log enable row level security;

drop policy if exists "read own zono activity" on public.zono_activity_log;
create policy "read own zono activity"
on public.zono_activity_log
for select to authenticated
using (user_id = auth.uid());

revoke insert, update, delete on public.zono_activity_log from anon, authenticated;
grant select on public.zono_activity_log to authenticated;

drop function if exists public.zono_add_activity_log(text,text,bigint,text,text);
create function public.zono_add_activity_log(
  p_kind text,
  p_resource text,
  p_amount bigint,
  p_title text,
  p_detail text default ''
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;

  delete from public.zono_activity_log
  where created_at < now() - interval '7 days';

  if p_kind not in ('counter_seed_reward','counter_feather_reward') then
    return;
  end if;

  if p_resource not in ('seed','feather') then
    raise exception 'نوع الرصيد غير صحيح';
  end if;

  insert into public.zono_activity_log(user_id,kind,resource,amount,title,detail)
  values(auth.uid(),p_kind,p_resource,coalesce(p_amount,0),
         left(coalesce(p_title,'مكافأة العداد'),120),
         left(coalesce(p_detail,''),500));
end;
$$;

drop function if exists public.zono_my_activity_log();
create function public.zono_my_activity_log()
returns table(
  id bigint,
  kind text,
  resource text,
  amount bigint,
  title text,
  detail text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
begin
  delete from public.zono_activity_log
  where created_at < now() - interval '7 days';

  return query
  select l.id,l.kind,l.resource,l.amount,l.title,l.detail,l.created_at
  from public.zono_activity_log l
  where l.user_id=auth.uid()
    and l.kind in ('counter_seed_reward','counter_feather_reward')
    and l.created_at >= now() - interval '7 days'
  order by l.id desc
  limit 150;
end;
$$;

grant execute on function public.zono_add_activity_log(text,text,bigint,text,text) to authenticated;
grant execute on function public.zono_my_activity_log() to authenticated;

-- Notifications: 7-day retention and only official types.
drop function if exists public.zono_my_notifications();

create function public.zono_my_notifications()
returns table(
  id bigint,
  kind text,
  title text,
  body text,
  sender_public_id bigint,
  amount bigint,
  is_read boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
begin
  delete from public.zono_notifications
  where created_at < now() - interval '7 days';

  return query
  select n.id,n.kind,n.title,n.body,n.sender_public_id,
         n.amount,n.is_read,n.created_at
  from public.zono_notifications n
  where n.user_id=auth.uid()
    and n.created_at >= now() - interval '7 days'
    and n.kind in ('seed_transfer','support','developer_message','company_message')
  order by n.id desc
  limit 100;
end;
$$;

drop function if exists public.zono_mark_notification_read(bigint);
create function public.zono_mark_notification_read(p_notification_id bigint)
returns void
language sql
security definer
set search_path=public
as $$
  update public.zono_notifications
  set is_read=true
  where id=p_notification_id
    and user_id=auth.uid();
$$;

grant execute on function public.zono_my_notifications() to authenticated;
grant execute on function public.zono_mark_notification_read(bigint) to authenticated;

notify pgrst,'reload schema';
