-- ZONO account center activity log
-- Run once in Supabase SQL Editor.

create table if not exists public.zono_activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'activity',
  resource text not null check (resource in ('seed','feather')),
  amount bigint not null default 0,
  title text not null,
  detail text not null default '',
  created_at timestamptz not null default now()
);

alter table public.zono_activity_log enable row level security;

drop policy if exists "read own zono activity" on public.zono_activity_log;
create policy "read own zono activity"
on public.zono_activity_log
for select to authenticated
using (user_id = auth.uid());

revoke insert, update, delete on public.zono_activity_log from anon, authenticated;
grant select on public.zono_activity_log to authenticated;

drop function if exists public.zono_add_activity_log(text,text,bigint,text,text);
create function public.zono_add_activity_log(
  p_kind text,
  p_resource text,
  p_amount bigint,
  p_title text,
  p_detail text default ''
) returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول'; end if;
  if p_resource not in ('seed','feather') then raise exception 'نوع الرصيد غير صحيح'; end if;

  insert into public.zono_activity_log(user_id,kind,resource,amount,title,detail)
  values(
    auth.uid(),
    left(coalesce(p_kind,'activity'),40),
    p_resource,
    coalesce(p_amount,0),
    left(coalesce(p_title,'عملية'),120),
    left(coalesce(p_detail,''),500)
  );
end;
$$;

drop function if exists public.zono_my_activity_log();
create function public.zono_my_activity_log()
returns table(
  id bigint,
  kind text,
  resource text,
  amount bigint,
  title text,
  detail text,
  created_at timestamptz
)
language sql
security definer
set search_path=public
as $$
  select l.id,l.kind,l.resource,l.amount,l.title,l.detail,l.created_at
  from public.zono_activity_log l
  where l.user_id=auth.uid()
  order by l.id desc
  limit 100;
$$;

grant execute on function public.zono_add_activity_log(text,text,bigint,text,text) to authenticated;
grant execute on function public.zono_my_activity_log() to authenticated;

notify pgrst,'reload schema';
