-- Zuno database v1.0
create extension if not exists pgcrypto;
create sequence if not exists public.zuno_public_id_seq start 1000 increment 1 minvalue 1000;
create sequence if not exists public.zuno_room_id_seq start 1000 increment 1 minvalue 1000;

create table if not exists public.profiles(
  id uuid primary key references auth.users(id) on delete cascade,
  public_id bigint unique not null default nextval('public.zuno_public_id_seq'),
  display_name text not null,
  avatar_url text,
  points bigint not null default 0 check(points>=0),
  gems bigint not null default 0 check(gems>=0),
  role text not null default 'user' check(role in('user','developer','admin')),
  inviter_public_id bigint,
  name_changed_at timestamptz,
  email_changed_at timestamptz,
  password_changed_at timestamptz,
  counter_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen timestamptz not null default now()
);
create index if not exists profiles_public_id_idx on public.profiles(public_id);

create or replace function public.zuno_handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
declare v_name text; v_invite bigint;
begin
  v_name:=nullif(trim(coalesce(new.raw_user_meta_data->>'display_name','')),'');
  v_invite:=nullif(regexp_replace(coalesce(new.raw_user_meta_data->>'invite_id',''),'\D','','g'),'')::bigint;
  if v_name is null then v_name:=split_part(coalesce(new.email,'user'),'@',1); end if;
  if v_invite is not null and not exists(select 1 from profiles where public_id=v_invite) then raise exception 'ID الدعوة غير موجود'; end if;
  insert into profiles(id,display_name,inviter_public_id) values(new.id,v_name,v_invite) on conflict(id) do nothing;
  return new;
end $$;
drop trigger if exists zuno_on_auth_user_created on auth.users;
create trigger zuno_on_auth_user_created after insert on auth.users for each row execute procedure public.zuno_handle_new_user();

alter table public.profiles enable row level security;
drop policy if exists "own profile select" on public.profiles;
create policy "own profile select" on public.profiles for select to authenticated using(id=auth.uid());
revoke insert,update,delete on public.profiles from anon,authenticated;
grant select on public.profiles to authenticated;

create or replace function public.zuno_invite_exists(p_invite_id bigint) returns boolean language sql security definer set search_path=public as $$select exists(select 1 from profiles where public_id=p_invite_id)$$;
grant execute on function public.zuno_invite_exists(bigint) to anon,authenticated;

create or replace function public.zuno_update_display_name(p_name text) returns void language plpgsql security definer set search_path=public as $$
declare p profiles%rowtype;
begin select * into p from profiles where id=auth.uid() for update; if not found then raise exception 'الحساب غير موجود'; end if;
if p.name_changed_at is not null and p.name_changed_at>now()-interval '7 days' then raise exception 'يمكن تغيير الاسم مرة كل 7 أيام'; end if;
if length(trim(p_name))<2 or length(trim(p_name))>40 then raise exception 'الاسم من 2 إلى 40 حرفاً'; end if;
update profiles set display_name=trim(p_name),name_changed_at=now(),updated_at=now() where id=auth.uid(); end $$;
create or replace function public.zuno_update_avatar(p_avatar_url text) returns void language plpgsql security definer set search_path=public as $$begin update profiles set avatar_url=nullif(trim(p_avatar_url),''),updated_at=now() where id=auth.uid(); end$$;
grant execute on function public.zuno_update_display_name(text),public.zuno_update_avatar(text) to authenticated;

create or replace function public.zuno_referral_count() returns bigint language sql security definer set search_path=public as $$select count(*) from profiles where inviter_public_id=(select public_id from profiles where id=auth.uid())$$;
create or replace function public.zuno_ping_presence() returns void language sql security definer set search_path=public as $$update profiles set last_seen=now() where id=auth.uid()$$;
grant execute on function public.zuno_referral_count(),public.zuno_ping_presence() to authenticated;

create or replace function public.zuno_start_counter() returns void language plpgsql security definer set search_path=public as $$
declare s timestamptz; begin select counter_started_at into s from profiles where id=auth.uid() for update; if s is not null then raise exception 'العداد مفعّل بالفعل أو المكافأة جاهزة'; end if; update profiles set counter_started_at=now(),updated_at=now() where id=auth.uid(); end$$;
create or replace function public.zuno_claim_counter_reward() returns jsonb language plpgsql security definer set search_path=public as $$
declare s timestamptz; g bigint; begin select counter_started_at into s from profiles where id=auth.uid() for update; if s is null then raise exception 'فعّل العداد أولاً'; end if; if s>now()-interval '24 hours' then raise exception 'لم تكتمل 24 ساعة بعد'; end if; update profiles set gems=gems+50,counter_started_at=null,updated_at=now() where id=auth.uid() returning gems into g; return jsonb_build_object('ok',true,'reward',50,'gems',g); end$$;
grant execute on function public.zuno_start_counter(),public.zuno_claim_counter_reward() to authenticated;

create table if not exists public.friend_requests(
 id uuid primary key default gen_random_uuid(),sender_id uuid not null references profiles(id) on delete cascade,receiver_id uuid not null references profiles(id) on delete cascade,note varchar(120),status text not null default 'pending' check(status in('pending','accepted','rejected')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(sender_id<>receiver_id));
create unique index if not exists one_pending_friend_request on friend_requests(least(sender_id,receiver_id),greatest(sender_id,receiver_id)) where status='pending';
alter table friend_requests enable row level security;create policy "friend request parties" on friend_requests for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());revoke insert,update,delete on friend_requests from authenticated;

create or replace function public.zuno_find_user(p_public_id bigint) returns table(public_id bigint,display_name text,avatar_url text,is_online boolean) language sql security definer set search_path=public as $$select p.public_id,p.display_name,p.avatar_url,(p.last_seen>now()-interval '2 minutes') from profiles p where p.public_id=p_public_id and p.id<>auth.uid()$$;
create or replace function public.zuno_send_friend_request(p_public_id bigint,p_note text default null) returns void language plpgsql security definer set search_path=public as $$declare target uuid;begin select id into target from profiles where public_id=p_public_id;if target is null then raise exception 'المستخدم غير موجود';end if;if target=auth.uid() then raise exception 'لا يمكنك إضافة نفسك';end if;if exists(select 1 from friend_requests where status='accepted' and ((sender_id=auth.uid() and receiver_id=target) or (sender_id=target and receiver_id=auth.uid()))) then raise exception 'هذا المستخدم صديق بالفعل';end if;insert into friend_requests(sender_id,receiver_id,note) values(auth.uid(),target,nullif(trim(p_note),''));end$$;
create or replace function public.zuno_pending_friend_requests() returns table(request_id uuid,public_id bigint,display_name text,avatar_url text,note text,created_at timestamptz) language sql security definer set search_path=public as $$select r.id,p.public_id,p.display_name,p.avatar_url,r.note,r.created_at from friend_requests r join profiles p on p.id=r.sender_id where r.receiver_id=auth.uid() and r.status='pending' order by r.created_at desc$$;
create or replace function public.zuno_respond_friend_request(p_request_id uuid,p_action text) returns void language plpgsql security definer set search_path=public as $$begin if p_action not in('accepted','rejected') then raise exception 'إجراء غير صحيح';end if;update friend_requests set status=p_action,updated_at=now() where id=p_request_id and receiver_id=auth.uid() and status='pending';if not found then raise exception 'الطلب غير موجود';end if;end$$;
create or replace function public.zuno_get_friends() returns table(public_id bigint,display_name text,avatar_url text,is_online boolean) language sql security definer set search_path=public as $$select p.public_id,p.display_name,p.avatar_url,(p.last_seen>now()-interval '2 minutes') from friend_requests r join profiles p on p.id=case when r.sender_id=auth.uid() then r.receiver_id else r.sender_id end where r.status='accepted' and (r.sender_id=auth.uid() or r.receiver_id=auth.uid()) order by p.display_name$$;
grant execute on function public.zuno_find_user(bigint),public.zuno_send_friend_request(bigint,text),public.zuno_pending_friend_requests(),public.zuno_respond_friend_request(uuid,text),public.zuno_get_friends() to authenticated;

create table if not exists public.private_messages(id bigint generated always as identity primary key,sender_id uuid not null references profiles(id) on delete cascade,receiver_id uuid not null references profiles(id) on delete cascade,body varchar(2000) not null,created_at timestamptz not null default now());alter table private_messages enable row level security;create policy "private chat parties" on private_messages for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());revoke insert,update,delete on private_messages from authenticated;
create or replace function public.zuno_are_friends(a uuid,b uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from friend_requests where status='accepted' and ((sender_id=a and receiver_id=b) or(sender_id=b and receiver_id=a)))$$;
create or replace function public.zuno_send_private_message(p_public_id bigint,p_body text) returns void language plpgsql security definer set search_path=public as $$declare t uuid;begin select id into t from profiles where public_id=p_public_id;if t is null then raise exception 'المستخدم غير موجود';end if;if not zuno_are_friends(auth.uid(),t) then raise exception 'المراسلة متاحة للأصدقاء فقط';end if;if length(trim(p_body))<1 or length(trim(p_body))>2000 then raise exception 'الرسالة غير صالحة';end if;insert into private_messages(sender_id,receiver_id,body)values(auth.uid(),t,trim(p_body));end$$;
create or replace function public.zuno_get_private_messages(p_public_id bigint) returns table(sender_public_id bigint,body text,created_at timestamptz) language sql security definer set search_path=public as $$select ps.public_id,m.body,m.created_at from private_messages m join profiles ps on ps.id=m.sender_id join profiles other on other.public_id=p_public_id where ((m.sender_id=auth.uid() and m.receiver_id=other.id)or(m.sender_id=other.id and m.receiver_id=auth.uid())) and zuno_are_friends(auth.uid(),other.id) order by m.created_at asc limit 300$$;
grant execute on function public.zuno_send_private_message(bigint,text),public.zuno_get_private_messages(bigint) to authenticated;

create table if not exists public.rooms(id uuid primary key default gen_random_uuid(),room_public_id bigint unique not null default nextval('public.zuno_room_id_seq'),owner_id uuid not null references profiles(id) on delete cascade,name varchar(60) not null,image_url text,bio varchar(300),password_hash text,created_at timestamptz not null default now());
create table if not exists public.room_members(room_id uuid references rooms(id) on delete cascade,user_id uuid references profiles(id) on delete cascade,member_role text not null default 'member' check(member_role in('owner','moderator','member')),muted_until timestamptz,muted_permanent boolean not null default false,is_banned boolean not null default false,joined_at timestamptz not null default now(),primary key(room_id,user_id));
create table if not exists public.room_messages(id bigint generated always as identity primary key,room_id uuid references rooms(id) on delete cascade,sender_id uuid references profiles(id) on delete cascade,body varchar(2000) not null,created_at timestamptz not null default now());
alter table rooms enable row level security;alter table room_members enable row level security;alter table room_messages enable row level security;create policy "rooms readable" on rooms for select to authenticated using(true);create policy "members readable" on room_members for select to authenticated using(true);create policy "room messages readable" on room_messages for select to authenticated using(true);revoke insert,update,delete on rooms,room_members,room_messages from authenticated;
create or replace function public.zuno_create_room(p_name text,p_image_url text default null,p_bio text default null,p_password text default null) returns bigint language plpgsql security definer set search_path=public as $$declare r rooms%rowtype; pts bigint;begin if length(trim(p_name))<2 then raise exception 'اسم الروم قصير';end if;if p_password is not null and p_password<>'' and p_password!~'^\d{1,4}$' then raise exception 'الرقم السري من 1 إلى 4 أرقام';end if;select points into pts from profiles where id=auth.uid() for update;if pts<500 then raise exception 'رصيد النقاط غير كافٍ';end if;update profiles set points=points-500,updated_at=now() where id=auth.uid();insert into rooms(owner_id,name,image_url,bio,password_hash)values(auth.uid(),trim(p_name),nullif(trim(p_image_url),''),nullif(trim(p_bio),''),case when coalesce(p_password,'')='' then null else crypt(p_password,gen_salt('bf')) end)returning * into r;insert into room_members(room_id,user_id,member_role)values(r.id,auth.uid(),'owner');return r.room_public_id;exception when others then raise;end$$;
create or replace function public.zuno_list_rooms() returns table(room_public_id bigint,name text,bio text,image_url text,owner_public_id bigint,is_locked boolean) language sql security definer set search_path=public as $$select r.room_public_id,r.name,r.bio,r.image_url,p.public_id,(r.password_hash is not null) from rooms r join profiles p on p.id=r.owner_id order by r.created_at desc limit 100$$;
create or replace function public.zuno_search_rooms(p_query bigint) returns table(room_public_id bigint,name text,bio text,image_url text,owner_public_id bigint,is_locked boolean) language sql security definer set search_path=public as $$select r.room_public_id,r.name,r.bio,r.image_url,p.public_id,(r.password_hash is not null) from rooms r join profiles p on p.id=r.owner_id where r.room_public_id=p_query or p.public_id=p_query order by r.created_at desc$$;
create or replace function public.zuno_join_room(p_room_public_id bigint,p_password text default null) returns boolean language plpgsql security definer set search_path=public as $$declare r rooms%rowtype;m room_members%rowtype;begin select * into r from rooms where room_public_id=p_room_public_id;if not found then raise exception 'الروم غير موجود';end if;select * into m from room_members where room_id=r.id and user_id=auth.uid();if found and m.is_banned then raise exception 'أنت محظور من هذا الروم';end if;if r.password_hash is not null and (p_password is null or crypt(p_password,r.password_hash)<>r.password_hash) then raise exception 'الرقم السري غير صحيح';end if;insert into room_members(room_id,user_id)values(r.id,auth.uid())on conflict(room_id,user_id)do update set joined_at=now();return true;end$$;
create or replace function public.zuno_room_details(p_room_public_id bigint) returns table(room_public_id bigint,name text,bio text,image_url text,owner_public_id bigint,owner_name text) language sql security definer set search_path=public as $$select r.room_public_id,r.name,r.bio,r.image_url,p.public_id,p.display_name from rooms r join profiles p on p.id=r.owner_id where r.room_public_id=p_room_public_id$$;
create or replace function public.zuno_room_members(p_room_public_id bigint) returns table(public_id bigint,display_name text,avatar_url text,member_role text,is_online boolean) language sql security definer set search_path=public as $$select p.public_id,p.display_name,p.avatar_url,m.member_role,(p.last_seen>now()-interval '2 minutes') from rooms r join room_members m on m.room_id=r.id join profiles p on p.id=m.user_id where r.room_public_id=p_room_public_id and not m.is_banned order by case m.member_role when 'owner' then 1 when 'moderator' then 2 else 3 end,p.display_name$$;
create or replace function public.zuno_send_room_message(p_room_public_id bigint,p_body text) returns void language plpgsql security definer set search_path=public as $$declare r uuid;m room_members%rowtype;begin select id into r from rooms where room_public_id=p_room_public_id;if r is null then raise exception 'الروم غير موجود';end if;select * into m from room_members where room_id=r and user_id=auth.uid();if not found then raise exception 'ادخل الروم أولاً';end if;if m.is_banned then raise exception 'أنت محظور';end if;if m.muted_permanent or (m.muted_until is not null and m.muted_until>now()) then raise exception 'أنت مكتوم حالياً';end if;insert into room_messages(room_id,sender_id,body)values(r,auth.uid(),trim(p_body));end$$;
create or replace function public.zuno_get_room_messages(p_room_public_id bigint) returns table(sender_public_id bigint,display_name text,member_role text,body text,created_at timestamptz) language sql security definer set search_path=public as $$select p.public_id,p.display_name,coalesce(m.member_role,'member'),msg.body,msg.created_at from rooms r join room_messages msg on msg.room_id=r.id join profiles p on p.id=msg.sender_id left join room_members m on m.room_id=r.id and m.user_id=msg.sender_id where r.room_public_id=p_room_public_id order by msg.created_at asc limit 300$$;
create or replace function public.zuno_room_action(p_room_public_id bigint,p_target_public_id bigint,p_action text,p_minutes int default null) returns void language plpgsql security definer set search_path=public as $$declare rid uuid;actor room_members%rowtype;target room_members%rowtype;tid uuid;begin select id into rid from rooms where room_public_id=p_room_public_id;if rid is null then raise exception 'الروم غير موجود';end if;select * into actor from room_members where room_id=rid and user_id=auth.uid();if actor.member_role not in('owner','moderator') then raise exception 'لا توجد صلاحية';end if;select id into tid from profiles where public_id=p_target_public_id;select * into target from room_members where room_id=rid and user_id=tid;if not found then raise exception 'العضو غير موجود';end if;if target.member_role='owner' then raise exception 'لا يمكن إدارة مالك الروم';end if;if actor.member_role='moderator' and target.member_role='moderator' then raise exception 'المشرف لا يدير مشرفاً آخر';end if;if p_action='promote' then if actor.member_role<>'owner' then raise exception 'المالك فقط يرفع المشرفين';end if;update room_members set member_role='moderator' where room_id=rid and user_id=tid;elsif p_action='demote' then if actor.member_role<>'owner' then raise exception 'المالك فقط ينزل المشرفين';end if;update room_members set member_role='member' where room_id=rid and user_id=tid;elsif p_action='mute_temp' then update room_members set muted_until=now()+make_interval(mins=>greatest(1,coalesce(p_minutes,10))),muted_permanent=false where room_id=rid and user_id=tid;elsif p_action='mute_perm' then update room_members set muted_permanent=true,muted_until=null where room_id=rid and user_id=tid;elsif p_action='unmute' then update room_members set muted_permanent=false,muted_until=null where room_id=rid and user_id=tid;elsif p_action='kick' then delete from room_members where room_id=rid and user_id=tid;elsif p_action='ban' then update room_members set is_banned=true where room_id=rid and user_id=tid;else raise exception 'إجراء غير معروف';end if;end$$;
grant execute on function public.zuno_create_room(text,text,text,text),public.zuno_list_rooms(),public.zuno_search_rooms(bigint),public.zuno_join_room(bigint,text),public.zuno_room_details(bigint),public.zuno_room_members(bigint),public.zuno_send_room_message(bigint,text),public.zuno_get_room_messages(bigint),public.zuno_room_action(bigint,bigint,text,int) to authenticated;

create table if not exists public.support_tickets(id uuid primary key default gen_random_uuid(),user_id uuid references profiles(id) on delete cascade,status text not null default 'open',created_at timestamptz not null default now());
create table if not exists public.support_messages(id bigint generated always as identity primary key,ticket_id uuid references support_tickets(id) on delete cascade,sender_id uuid references profiles(id) on delete cascade,body varchar(3000) not null,created_at timestamptz not null default now());alter table support_tickets enable row level security;alter table support_messages enable row level security;create policy "own support tickets" on support_tickets for select to authenticated using(user_id=auth.uid() or exists(select 1 from profiles p where p.id=auth.uid() and p.role in('developer','admin')));create policy "support messages visible" on support_messages for select to authenticated using(exists(select 1 from support_tickets t where t.id=ticket_id and (t.user_id=auth.uid() or exists(select 1 from profiles p where p.id=auth.uid() and p.role in('developer','admin')))));revoke insert,update,delete on support_tickets,support_messages from authenticated;
create or replace function public.zuno_create_support_ticket(p_message text) returns uuid language plpgsql security definer set search_path=public as $$declare tid uuid;begin if length(trim(p_message))<2 then raise exception 'الرسالة قصيرة';end if;insert into support_tickets(user_id)values(auth.uid())returning id into tid;insert into support_messages(ticket_id,sender_id,body)values(tid,auth.uid(),trim(p_message));return tid;end$$;grant execute on function public.zuno_create_support_ticket(text) to authenticated;

notify pgrst,'reload schema';
